FakeItEasy/FakeItEasy

Source/FakeItEasy.Tests/ATests.cs
Source/FakeItEasy/A.cs
Source/FakeItEasy/Fake.cs

Fixes #425.
These are all the _obsolete_ type members I could find. There are other types that could be made internal or moved to different namespaces, though. Unless there's an objection, I'll make another issue for those.

#425 remove obsolete type members

---

Source/FakeItEasy-SL/FakeItEasy-SL.csproj
Source/FakeItEasy-SL/packages.config
Source/FakeItEasy.Net35/FakeItEasy.Net35.csproj
Source/FakeItEasy.Net35/packages.config
Source/FakeItEasy/FakeItEasy.csproj
Source/FakeItEasy/packages.config

ILMerge 2.13.0307 was generating an invalid assembly (methods with missing
implementation) when merging assemblies built with the C# 6 compiler.
Version 2.14.1208 works as expected.

Updated ILMerge NuGet package

---

Source/FakeItEasy/Core/BootstrapperLocator.cs
Source/FakeItEasy/Core/TypeCatalogueInstanceProvider.cs
Source/FakeItEasy/Creation/DummyValueCreationSession.cs
Source/FakeItEasy/TypeExtensions.cs

Fixes #494.
Not every CreateInstance got the treatment, and try as I might, I couldn't think of reasonable unit/integration/acceptance tests…

avoiding attempts to create instances of abstract types

---

Source/FakeItEasy.Tests/Creation/DefaultFakeObjectCreatorTests.cs
Source/FakeItEasy/Core/DefaultFixtureInitializer.cs
Source/FakeItEasy/Core/DefaultSutInitializer.cs
Source/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs
Source/FakeItEasy/Creation/FakeOptions.cs
Source/FakeItEasy/RootModule.cs

Per @adamralph's [comment in #487](https://github.com/FakeItEasy/FakeItEasy/pull/487/files#r33120984):
> Minor point, but this constructor can be removed and replaced with field initializers.

removing FakeOptions's parameterless constructor

---

Source/FakeItEasy.Tests/Core/FakeWrapperConfiguratorTests.cs
Source/FakeItEasy.Tests/Creation/DefaultFakeCreatorTests.cs
Source/FakeItEasy.Tests/Creation/FakeOptionsConstraints.cs
Source/FakeItEasy.Tests/CustomArgumentConstraints.cs
Source/FakeItEasy/Core/FakeWrapperConfigurator.cs
Source/FakeItEasy/Creation/DefaultFakeCreatorFacade.cs
Source/FakeItEasy/Creation/FakeOptions.cs

I think an improvement over the arrangement introduced in #487.
@adamralph had [expressed doubts](https://github.com/FakeItEasy/FakeItEasy/pull/487#discussion_r32370948) about the mutable `FakeOptionsBuilder<T>.Recorder` field.
At the time, I couldn't think of a better alternative.
While preparing for #520, it seemed we'd be better off if `Wrapper` weren't on `FakeOptions`.
The change makes `FakeWrapperConfigurator` a stronger participant in the fluent fake configuration API.
I tried to preserve existing unit tests, but where it was super awkward, and where the conditions being tested were covered by all the new specs I'd added recently, I just dropped the tests.

moving wrapper from FakeOptions to FakeOptionsBuilder

---

Source/FakeItEasy.Specs/CreationOptionsSpecs.cs
Source/FakeItEasy.Tests/Creation/DefaultFakeCreatorTests.cs
Source/FakeItEasy/Creation/FakeOptions.cs

Modifications to throw when IFakeOptionsBuilder.Implements() is passed a non-interface
#462

#462 - Throw when IFakeOptionsBuilder.Implements is passed a non-interface

---

Source/FakeItEasy.Specs/CreationOptionsSpecs.cs

fixes a code analysis warning that I introduced in e884223d0ceb1034879e94513a67070b45f58602 / #546.

making CreationOptionsSpecs static

---

Source/FakeItEasy.Specs/AssertingOnSetOnlyPropertiesSpecs.cs
Source/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
Source/FakeItEasy.Specs/AsyncAwaitSpecs.cs
Source/FakeItEasy.Specs/CallMatchingSpecs.cs
Source/FakeItEasy.Specs/CallsBaseMethodsFakeSpecs.cs
Source/FakeItEasy.Specs/ConfigurationSpecs.cs
Source/FakeItEasy.Specs/CreationSpecs.cs
Source/FakeItEasy.Specs/DisposableSpecs.cs
Source/FakeItEasy.Specs/DummyFactorySpecs.cs
Source/FakeItEasy.Specs/FakeConfiguratorSpecs.cs
Source/FakeItEasy.Specs/FakeScopeSpecs.cs
Source/FakeItEasy.Specs/FakingDelegates.cs
Source/FakeItEasy.Specs/FakingInternalsSpecs.cs
Source/FakeItEasy.Specs/FixtureInitializationSpecs.cs
Source/FakeItEasy.Specs/LazySpecs.cs
Source/FakeItEasy.Specs/OrderedCallMatchingSpecs.cs
Source/FakeItEasy.Specs/PropertySpecs.cs
Source/FakeItEasy.Specs/SelfInitializedFakesSpecs.cs
Source/FakeItEasy.Specs/StrictFakeSpecs.cs
Source/FakeItEasy.Specs/UnconfiguredFakeSpecs.cs

It seems they work as static classes, so why not?
I'm about to hit a few Specs in my work on #461 and preferred not to mix the "staticking" in with the other changes.

making most specs static

---

rakefile.rb

Given that we're now pointing to Gitter as our official chat, and I recently changed the JabbR room topic to reflect that, posting in the FakeItEasy JabbR room is redundant.
I think it's still worth posting in JabbR general chat since a fair number of our community still hang out there.

remove link to FakeItEasy JabbR room

---

Source/FakeItEasy.Specs/FakeConfiguratorSpecs.cs
Source/FakeItEasy.Specs/FakeScopeSpecs.cs
Source/FakeItEasy.Specs/FixtureInitializationSpecs.cs

I'll be touching these in my #461 work, so I figured I might as well get them tidy beforehand. 
Besides, I get to practice my BDD naming.
First commit is a fairly straightforward "name things better". 
Then I saw improvements for `FixtureInitializationSpecs` and `FakeConfiguratorSpecs`

refactor: clean up some specs

---

Source/FakeItEasy/Core/AssemblyExtensions.cs
Source/FakeItEasy/Core/BootstrapperLocator.cs
Source/FakeItEasy/Core/TypeCatalogue.cs

In my hacks around Sledgehammer, I am dynamically creating objects using [Impromptu-interface](https://github.com/ekonbenefits/impromptu-interface), and using reflected FakeItEasy types to construct these object. This causes the FakeItEasy assembly to be added as a reference to the dynamic assembly, that is generated with Impromptu-interface.
This causes FIE to throw an exception during the Bootstrapper Locator scan: attempting to call `assembly.GetExportedTypes()` on a dynamic assembly throws a `NotSupportedException`. Since my generated dynamic assembly does indeed include a reference to FIE, it is picked up for scanning.
This PR adds a Where, excluding Dynamic assemblies from the scan.

Exclude dynamic assemblies from Bootstrapper Locator scan

---

Source/FakeItEasy/Core/TypeCatalogue.cs

The warning was introduced in 4081cba1a0f215e840122171a34f545d6e700759.

Fix style warning in TypeCatalogue docs

---

Source/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
Source/FakeItEasy.Specs/ConfigurationSpecs.cs
Source/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
Source/FakeItEasy.Tests/Expressions/ExpressionCallRuleTests.cs
Source/FakeItEasy/Configuration/BuildableCallRule.cs
Source/FakeItEasy/Configuration/RecordingRuleBuilder.cs
Source/FakeItEasy/Expressions/ExpressionCallRule.cs

Fixes #534.
Closes #557, which this PR supersedes.
I just rebased @thomaslevesque's commits after I caused a conflict with #568.
All I had to do was resolve the conflicting types for `wherePredicates` in BuildableCallRule.cs.
#557's original description:
> This is in order to prevent an unsupported scenario where the user keeps
> the result of A.CallTo(...) and uses it to define multiple behaviors.
> Doing so would override the existing behavior, not stack the new one,
> even though it's not necessarily what the user would expect. Making it
> illegal prevents confusion. It remains possible to keep the result of
> A.CallTo to make later calls to MustHaveHappened and friends.
> 
> See the comments in FakeItEasy/FakeItEasy#534 for more details.

Prevent redefine rule behavior

---

Source/FakeItEasy.Dictionary.Tests.xml
Source/FakeItEasy.Specs/TaskSpecs.cs

Add "dummyable" to the dictionary
Suppress warnings on `GetFooAsync` and `GetBarAsync` in `TaskSpecs`

Fix FxCop warnings

---

Source/FakeItEasy.IntegrationTests/DummyTests.cs
Source/FakeItEasy.Net35/FakeItEasy.Net35.csproj
Source/FakeItEasy.Specs/ArgumentValueFormatterSpecs.cs
Source/FakeItEasy.Specs/DummyFactorySpecs.cs
Source/FakeItEasy.Specs/FakeItEasy.Specs.csproj
Source/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
Source/FakeItEasy.Tests/Core/ArgumentValueFormatterTests.cs
Source/FakeItEasy.Tests/Core/DummyFactoryTests.cs
Source/FakeItEasy.Tests/Core/DynamicContainerTests.cs
Source/FakeItEasy.Tests/FakeItEasy.Tests.csproj
Source/FakeItEasy.Tests/FakeOptionsBuilderTests.cs
Source/FakeItEasy.Tests/PriorityTests.cs
Source/FakeItEasy/ArgumentValueFormatter.cs
Source/FakeItEasy/Core/ArgumentValueFormatter.cs
Source/FakeItEasy/DummyFactory.cs
Source/FakeItEasy/FakeItEasy.csproj
Source/FakeItEasy/FakeOptionsBuilder.cs
Source/FakeItEasy/IArgumentValueFormatter.cs
Source/FakeItEasy/IDummyFactory.cs
Source/FakeItEasy/IFakeOptionsBuilder.cs
Source/FakeItEasy/Priority.cs

Fixes #525.
Using a custom Priority type to ensure clients can only make non-negative priorities.

Rationalize priority values

---

rakefile.rb

Use MSBuild v12 if no MSBuild v14

---

docs/css/extra-highlight.css
docs/css/highlight.css
mkdocs.yml

This PR contributes to #626, and updates code styling by cherry-picking the last two commits from #634, which were applied to the 1.25.3 docs.
Preview at http://bfakeiteasy.readthedocs.org/en/read-the-docs-2.0/

Improve documentation code styling

---

src/FakeItEasy.Analyzer/UnusedCallSpecificationAnalyzer.cs
tests/FakeItEasy.Analyzer.Tests/UnusedCallSpecificationAnalyzerTests.cs

I couldn't find any guidelines about what we should use for diagnostic ids, but we should probably use numbered ids with a common prefix; that's what everyone else seems to be doing.
Also, should we change the default severity of the diagnostic to `Error` rather than `Warning` ? Ignoring the result of `CallTo` will almost certainly not be intentional. And it can always be overriden in the .ruleset file if necessary.
Connects to #490

Change analyzer diagnostic id to FakeItEasy001

---

src/FakeItEasy.Analyzer/DiagnosticDefinitions.cs
src/FakeItEasy/Core/ArgumentConstraintTrap.cs
tests/FakeItEasy.Analyzer.Tests/Helpers/CodeFixVerifier.cs
tests/FakeItEasy.Analyzer.Tests/Helpers/DiagnosticResult.cs
tests/FakeItEasy.Analyzer.Tests/Helpers/DiagnosticVerifier.cs
tests/FakeItEasy.Analyzer.Tests/UnusedCallSpecificationAnalyzerTests.cs
tests/FakeItEasy.Specs/TaskSpecs.cs

There were only a few places in the codebase where we having the namespace in-line, compared to many where we use a `using`, so I aligned everything to use a `using`.

refactor: move System.Diagnostics.CodeAnalysis to using statement

---

README.md

Point to readthedocs.io, not .org

---

src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
tests/FakeItEasy.Tests/Creation/DelegateProxies/DelegateProxyGeneratorTests.cs

Fixes #677
WIP because I still need to add specs
I took into account the other remarks from https://github.com/thomaslevesque/FakeItEasy/commit/5570756fa1dbefc872804ad7a80bf3ad87aa9f5d

Fix AssignsOutAndRefParameters for faked delegates

---

.gitignore
FakeItEasy.sln
rakefile.rb
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.cs
tests/FakeItEasy.Tests.Approval/FakeItEasy.Tests.Approval.csproj
tests/FakeItEasy.Tests.Approval/packages.config

closes #701 
It works like this:
* `tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt` contains the state of the public API when the approval test was last run and approved
* when you run `FakeItEasy.Tests.Approval.ApiApproval.ApproveApi` or `bundle exec rake approve`, the current state of the API will be written to `tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.received.txt`
* if the state differs, you will either be presented with a diff (when running from VS) or you will see a test  failure (when running from console)
* if you approve of the change, you update `ApiApproval.ApproveApi.approved.txt` with the contents of `ApiApproval.ApproveApi.received.txt` (if in a diff viewer, right click -> "use this file")
* you commit the changed …

add API approval test

---

Gemfile.lock

On the recommendation of http://rubyinstaller.org/downloads/ I took the conservative option and installed 32-bit Ruby on my new (64-bit) workstation:
> The 64-bit versions of Ruby are relatively new on the Windows area and not all the packages have been updated to be compatible with it. To use this version you will require some knowledge about compilers and solving dependency issues, which might be too complicated if you just want to play with the language.
(With Ruby, I don't want to do anything other than run Rake.)
Every time I run Bundler now it insists on adding these lines to Gemfile.lock so I'm bowing to the pressure and sending a PR for it. I don't think it will do any harm.

add 32-bit platform to Gemfile.lock

---

build.cmd
how_to_build.md

For convenience, also includes `bundle install`, although I'm in two minds about that. Thoughts?

add build.cmd as a shortcut for bundle exec rake

---

README.md

shields.io no longer supports it.
We could switch to https://buildstats.info/ but then we'd have to abandon the square badge style and go with rounded corners for all:
[![NuGet Badge](https://buildstats.info/nuget/FakeItEasy)](https://www.nuget.org/packages/FakeItEasy/)

remove nuget downloads badge

---

src/FakeItEasy.Analyzer/UnusedReturnValueAnalyzer.cs
tests/FakeItEasy.Analyzer.Tests/UnusedReturnValueAnalyzerTests.cs

e.g. `Foo()` instead of `this.Foo()`, or `CallTo(...)` instead of `A.CallTo(...)` (with `using static FakeItEasy.A`)
as discussed in #732

Support `using static FakeItEasy.A` in unused call specifications

---

docs/argument-constraints.md
docs/assigning-out-and-ref-parameters.md
docs/implicit-creation-options.md
docs/invoking-custom-code.md
docs/specifying-a-call-to-configure.md
docs/specifying-return-values.md
docs/throwing-exceptions.md

I was looking through the docs and spotted several things that looked strange
that's a minor thing but would help the docs to look consistent

fixed several syntax issues in documentation

---

docs/specifying-a-call-to-configure.md

Call out use of prefixes for property method names

---

src/FakeItEasy.Analyzer/UnusedReturnValueAnalyzer.cs
tests/FakeItEasy.Analyzer.Tests/UnusedReturnValueAnalyzerTests.cs

Update analyzer for calls to WithNonVoidReturnType

---

src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/Core/DelegateRaiser.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/FakeWrapperConfigurator.cs
src/FakeItEasy/Core/MethodInfoManager.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
src/FakeItEasy/Creation/DummyValueCreationSession.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/Expressions/ArgumentConstraints/OutArgumentConstraint.cs
src/FakeItEasy/Expressions/ArgumentConstraints/RefArgumentConstraint.cs
src/FakeItEasy/Expressions/ParsedArgumentExpression.cs
src/FakeItEasy/Fake.of.T.cs
src/FakeItEasy/SelfInitializedFakes/RecordingManager.cs
tests/FakeItEasy.Specs/UnconfiguredFakeSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/Core/DefaultSutInitializerTests.cs

Taking advantage of a little C# 6 to remove private setters from auto-props. While I was here, I noticed some getters that were effectively private. There are more, but on public classes. :disappointed:

Clean up properties

---

src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
src/FakeItEasy/Creation/IFakeAndDummyManager.cs

It's not used. Probably was missed from removal when we changed unconfigured fakes to always return Dummies. But that's just a guess.

Remove IFakeAndDummyManager.TryResolveDummyValue

---

rakefile.rb

Protects us against duplicate projects in case we ever add a second .sln.
See @jeremymeng's [AppVeyor build](https://ci.appveyor.com/project/jeremymeng/fakeiteasy/build/2.3.0-coreclr-alpha30#L476) for what I'm talking about. Or just build coreclr locally.

Specify sln file for gitlink to use

---

FakeItEasy-NetCore.sln
FakeItEasy.sln

Believe it or not, this isn't completely useless.
When you "open" the exe from the solution explorer, you get this:
If you then double-click the leaf under `Version`, you get:
I.e. you can check which version of nuget.exe we are running from inside VS!

add nuget.exe to solutions

---

tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/GlobalSuppressions.cs
tests/FakeItEasy.Specs/SelfInitializedFakesSpecs.cs
tests/FakeItEasy.Specs/WrappingFakeSpecs.cs
tests/FakeItEasy.Tests.ruleset
tests/FakeItEasy.Tests/Core/WrappedObjectRuleTests.cs
tests/FakeItEasy.Tests/IFoo.cs
tests/FakeItEasy.Tests/IOutputAndRef.cs
tests/FakeItEasy.Tests/OutAndRefParametersConfigurationExtensionsTests.cs
tests/FakeItEasy.Tests/ReturnValueConfigurationExtensionsTests.cs

FakeItEasy must work with a variety of client code that doesn't conform to
some coding "best practices". As such, our test need to include types that
likewise violate these rules. Including suppression statements for the
more common of the rules is tiresome and clutters the code, so move some
out into the global ruleset:
- CA1021: AvoidOutParameters
- CA1045: DoNotPassTypesByReference
- CA1062: ValidateArgumentsOfPublicMethods
- CA1716: IdentifiersShouldNotMatchKeywords

Suppress harmless diagnostics for test projects

---

tests/FakeItEasy.Analyzer.Tests/Helpers/DiagnosticVerifier.Helper.cs
tests/FakeItEasy.Analyzer.Tests/UnusedReturnValueAnalyzerTests.cs

Fixes #843.
The test code documents we feed into the analyzer as part of the unit
tests should be as close to real code as is practical. In particular,
the code should use FakeItEasy properly. Ensureing that the code compiles
is a good first step.

Ensure analyzer test code snippets compile

---

src/FakeItEasy/Configuration/RuleBuilder.cs

instead of reimplementing it separately
Similar to the [change](https://github.com/FakeItEasy/FakeItEasy/pull/840/files#diff-6d9562889008c1f9bfad045e9078aba0R150) made in #840, but I moved this one to a separate PR since it wasn't related to the original PR.

Call WhenArgumentsMatch on parent configuration

---

src/FakeItEasy/ExpressionExtensions.cs

...from by 'AssertThatMemberCanBeIntercepted' during trivial A.CallTo() specifications, like
```
var fake = A.Fake<X>();
A.CallTo(() => fake.DoStuff();
```
Fixes #850

Optimize away some calls to DynamicMethod.CreateDelegate() 

---

appveyor.yml
rakefile.netstd.rb
rakefile.rb

I think it's important that we increment our package number each time a new package is created in our AppVeyor NuGet feed. This PR appends the build number to it. Otherwise, each time a PR is merged, the -netstd packages are replaced in the NuGet feed, and anyone restoring them will be silently upgraded.
This will also affect pre-release packages of the regular (non -netstd) packages, but appending a build number to these is also common practice, e.g. https://www.nuget.org/packages/xunit/2.2.0-beta2-build3300.

add build suffix to pre-release packages

---

docs/creating-fakes.md
src/FakeItEasy.netstd/project.json
src/FakeItEasy/Core/FakeWrapperConfigurator.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs
src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
src/FakeItEasy/Creation/FakeOptionsBase.cs
src/FakeItEasy/Creation/IFakeOptions.cs
src/FakeItEasy/Creation/IFakeOptions.of.T.cs
src/FakeItEasy/Creation/IProxyGenerator.cs
src/FakeItEasy/Creation/IProxyOptions.cs
src/FakeItEasy/Creation/ProxyGeneratorSelector.cs
src/FakeItEasy/Creation/ProxyOptions.cs
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/packages.config
tests/FakeItEasy.IntegrationTests/GeneralTests.cs
tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests.netstd/project.json
tests/FakeItEasy.Tests/Creation/DefaultFakeObjectCreatorTests.cs
tests/FakeItEasy.Tests/CustomArgumentConstraints.cs
wrap/FakeItEasy/project.json

Fixes #436 
The only visible API change is `IFakeOptions.WithAdditionalAttributes`, which now takes a `params Expression<Func<Attribute>>[]`.

Upgrade to Castle.Core 4.0.0-beta002

---

FakeItEasy.netstd.sln
rakefile.netstd.rb
src/FakeItEasy/Core/AssemblyExtensions.cs
src/FakeItEasy/Core/TypeCatalogue.cs
tests/FakeItEasy.IntegrationTests.External.netstd/FakeItEasy.IntegrationTests.External.netstd.xproj
tests/FakeItEasy.IntegrationTests.External.netstd/project.json
tests/FakeItEasy.IntegrationTests.netstd/FakeItEasy.IntegrationTests.netstd.xproj
tests/FakeItEasy.IntegrationTests.netstd/project.json
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.IntegrationTests/FakingClassesTests.cs
tests/FakeItEasy.IntegrationTests/GeneralTests.cs
tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs

Connects to #531.
Was finally able to clear (IMO) the last couple hurdles after @jeremymeng's work to add integration tests to the .NET Standard build.
In the end I'd probably squash the whole bit, but I wanted you to be able to see the first commit, which @jermeymeng gets credit for (I tweaked slightly so we could rebase), and the others, which I get blame for.
The most interesting thing is that when loading assemblies from files, the .NET Standard loader does not error out if you load the same assembly from different paths. Hence the skipping of `Should_warn_of_duplicate_input_assemblies_with_different_paths`.
Oh! And our original method of telling whether an assembly reference FakeItEasy did not work for assemblies explicitly loaded from files (the so-called "external" assemblies). …

Integration tests for .NET Standard build

---

rakefile.rb

Fixes #913, I think.
1. no need to de-list pre-release packages
2. no need to post link to release in each issue for pre-release versions
3. always attach and publish both nupkgs
4. split out instruction to post tweet here
5. better wording around proper VERSION_SUFFIX environment variable on AppVeyor

Update release issue steps

---

src/FakeItEasy.netstd/FakeItEasy.netstd.csproj
src/FakeItEasy/Core/FakeWrapperConfigurator.cs
src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
src/FakeItEasy/Creation/FakeOptionsBase.cs
src/FakeItEasy/Creation/IFakeOptions.cs
src/FakeItEasy/Creation/IFakeOptions.of.T.cs
src/FakeItEasy/Creation/IFakeOptionsForWrappers.cs
src/FakeItEasy/Creation/IFakeOptionsForWrappers.of.T.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt

Remove IFakeOptionsForWrappers from .NET Standard

---

src/FakeItEasy.netstd/FakeItEasy.netstd.csproj
src/FakeItEasy/RootModule.cs

They're only used by self-initializing fakes

Remove IFileSystem, FileSystem from .NET Standard build

---

src/FakeItEasy/Core/FakeWrapperConfigurator.cs
src/FakeItEasy/Creation/IFakeOptionsForWrappers.cs
src/FakeItEasy/Creation/IFakeOptionsForWrappers.of.T.cs
src/FakeItEasy/IFileSystem.cs
src/FakeItEasy/Recorders.cs
src/FakeItEasy/RootModule.cs
src/FakeItEasy/SelfInitializedFakes/CallData.cs
src/FakeItEasy/SelfInitializedFakes/FileStorage.cs
src/FakeItEasy/SelfInitializedFakes/ICallStorage.cs
src/FakeItEasy/SelfInitializedFakes/ISelfInitializingFakeRecorder.cs
src/FakeItEasy/SelfInitializedFakes/RecordingException.cs
src/FakeItEasy/SelfInitializedFakes/RecordingManager.cs
src/FakeItEasy/SelfInitializedFakes/SelfInitializationRule.cs
tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
tests/FakeItEasy.Specs/SelfInitializedFakesSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/Core/FakeWrapperConfiguratorTests.cs
tests/FakeItEasy.Tests/RecordersTests.cs
tests/FakeItEasy.Tests/SelfInitializedFakes/CallDataTests.cs
tests/FakeItEasy.Tests/SelfInitializedFakes/FileStorageTests.cs
tests/FakeItEasy.Tests/SelfInitializedFakes/RecordingExceptionTests.cs
tests/FakeItEasy.Tests/SelfInitializedFakes/RecordingManagerTests.cs
tests/FakeItEasy.Tests/SelfInitializedFakes/SelfInitializationRuleTests.cs

To be removed in 4.0.0.
Fixes #820.

Mark all Self-Initializing Fake types and members as obsolete

---

src/FakeItEasy.nuspec

Without this, consumers of our package find 
```
System.MissingMethodException : Method not found: 'System.Collections.Generic.IList`1<Castle.DynamicProxy.CustomAttributeInfo> Castle.DynamicProxy.ProxyGenerationOptions.get_AdditionalAttributes()'.
```

Update Castle.Core netstd dependency to match project.json

---

how_to_build.md

In #909 @blairconrad removed `build.netstd.cmd`.
In this PR I removed all mentions of `build.netstd.cmd` from docs.

Remove build.netstd.cmd from docs

---

docs/default-fake-behavior.md
src/FakeItEasy.netstd/FakeItEasy.netstd.csproj
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/Core/FakeManager.CancellationRule.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/TaskHelper.cs
tests/FakeItEasy.Specs/CancellationSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/CancellationTokenConstraintTestsBase.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/CancellationTokenIsCancelledTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/CancellationTokenIsNotCancelledTests.cs
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Fixes #904 
By default, calls that receive a cancelled `CancellationToken` argument will either:
- throw an `OperationCancelledException` (for synchronous methods)
- return a cancelled `Task` (for asynchronous methods)
This behavior will be overridden if the call is explicitly configured. To avoid this, the `CancellationToken` argument should be constrained to be not cancelled; a new `IsNotCancelled` extension method is provided as a shortcut for this scenario:
```
A.CallTo(() => foo.Bar(A<CancellationToken>.That.IsNotCancelled())).Returns(42);
```
A symmetric `IsCancelled` extension method is also available.

Automatic cancellation behavior

---

appveyor.yml

Reverts cb0edf0e6402b97141c71bc6c0035c86b4093fe2 because 
the bug reported in  https://github.com/appveyor/ci/issues/1202
has been fixed.

Build on new AppVeyor VS2015 image

---

CONTRIBUTING.md
rakefile.rb

… because there was no good example, and it would be very easy to supply the "wrong" parameter, e.g. 3.0.0-beta003 instead of just beta003
I suppose the task could validate the input, but I am lazy. And did not think of it 'til now.

Improve pre-release example

---

appveyor.yml

1. we don't need the netstd build, and
2. the netstd build appends `-adhoc` to the version number, so we'd've had to change _something_

Have AppVeyor just build .NET Desktop version

---

tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs

Some tests were failing when run from ReSharper. I think this is because it shadow copies assemblies, so the `Location` isn't the original location. Using `CodeBase` instead fixes it.

Fix integration tests for external assembly

---

.gitignore

The `.user` files for the new shared projects (`.shproj`) weren't ignored; I updated the `.gitignore` to ignore all `*.*proj.user` files.

Ignore all per-user project settings files

---

src/FakeItEasy.Analyzer.Shared/UnusedReturnValueAnalyzer.cs
src/FakeItEasy.netstd/FakeItEasy.netstd.csproj
src/FakeItEasy/Configuration/FakeConfigurationManager.cs
src/FakeItEasy/Configuration/IStartConfiguration.cs
src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Configuration/StartConfiguration.cs
src/FakeItEasy/Expressions/CallExpressionParser.cs
src/FakeItEasy/Expressions/ICallExpressionParser.cs
src/FakeItEasy/Fake.of.T.cs
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.Specs/UnnaturalFakeSpecs.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt

Fixes #838 
I did a bit of refactoring to make `StartConfiguration` work more like `FakeConfigurationManager`.
I also had to change `CallExpressionParser` to work correctly with unnatural fakes. The call specification expression takes a parameter, so calling `ParsedCallExpression.CallTarget` was trying to evaluate an expression that was a `ParameterExpression`, which of course didn't work since the parameter value was unknown. I added a `ICallExpression.Parse` overload that accepts the fake itself and rewrites the expression from `f => f.TheMethod()` to `() => <value of fake.FakeObject>.TheMethod()`.

Add CallsToSet to unnatural fakes

---

FakeItEasy.sln

FakeItEasy.IntegrationTests.External.netstd sometimes fails to build when using the Rebuild command in Visual Studio. MSBuild tries to build it too early, before FakeItEasy.netstd has been built. Adding an explicit build dependency in the solution fixes the problem.

Add explicit dependency to fix build issue

---

docs/default-fake-behavior.md
docs/read-write-property-behavior.md
mkdocs.yml
src/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs
src/FakeItEasy/Core/FakeManager.PropertyBehaviorRule.cs
src/FakeItEasy/Core/FakeManager.PropertySetterRule.cs
src/FakeItEasy/Core/FakeManager.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/ReadWritePropertySpecs.cs
tests/FakeItEasy.Tests/Core/FakeManagerTests.cs

This PR is an experiment to demonstrate a new behavior for "auto properties", as discussed in the chat.
Fixes #962

Change behavior of auto properties to not override explicit configuration

---

rakefile.rb
src/FakeItEasy.nuspec

Forgot the nuspec in #974...
Also, the `-adhoc` default version suffix was only necessary when the Castle.Core dependency was a pre-release version, so I removed it (I set the VERSION_SUFFIX to `-rc001` in AppVeyor)

Fix nuspec castle version

---

docs/raising-events.md
src/FakeItEasy/Core/Raise.of.TEventArgs.cs
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/Raise.cs
tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt

Stop requiring event args to extend EventArgs (for .NET Standard)

---

src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/Configuration/AnyCallCallRule.cs
src/FakeItEasy/Core/FakeManager.ObjectMemberRule.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/FakeObjectCallExtensions.cs
src/FakeItEasy/TypeExtensions.cs
src/FakeItEasy/ValueProducerSignatureHelper.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Tests/NullGuardedAssertion.cs

Use Type.ToString() instead of Type.FullName in call descriptions

---

docs/platform-support.md

Arising from a recent question in Gitter, I send in this pull request to improve the documentation that we officially support .NET Standard 1.6.

Improved docs: Added .NET Standard 1.6 as supported platform

---

src/FakeItEasy/Core/FakeWrapperConfigurator.cs

- SA1001 : CSharp.Spacing : Invalid spacing around the comma.
connects to #914

fix stylecop violation

---

src/FakeItEasy/Core/DefaultFakeManagerAccessor.cs
src/FakeItEasy/ExceptionMessages.Designer.cs
src/FakeItEasy/ExceptionMessages.resx
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Tests/Core/DefaultFakeManagerAccessorTests.cs

Fixes #530.
Added more detailed object exception output for proxy and its tag when they are not recognized as a fake, and moved the exception message to the resx. Adjusted unit tests to match.

Added more detailed object exception output for proxy and its tag

---

tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.IntegrationTests/Properties/XunitAssemblyInfo.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/Properties/XunitAssemblyInfo.cs
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj
tests/FakeItEasy.Tests/Properties/XunitAssemblyInfo.cs

Fixes #774.
As discussed with @blairconrad in chat
~~Some unit tests couldn't run in parallel because they mutated global state (`ServiceLocator.Current`). Making them part of the same test collection fixes the problem.~~ (fixed in #1029)
Specs and integration tests seem to have no problem running in parallel.

Enable test parallelization

---

tests/FakeItEasy.Specs/ObjectCallSpecs.cs

"unindenter" should've begun with "U". Of course that conflicts with the type name, so I just moved the instance.

Fix name warning for unindenter

---

src/FakeItEasy/Configuration/ArgumentCollection.cs
src/FakeItEasy/ExceptionMessages.cs

CA2208: Instantiate argument exceptions correctly
I remove the parameter name, because it's not one argument that is incorrect, but the fact that the arguments are mismatched. I also changed the exception message which no longer made sense.

Fix code analysis warning

---

tests/FakeItEasy.Tests.ruleset

It was mistakenly re-enabled in #1026

Disable CA1822 code analysis warning

---

tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs

We were invoking A.Fake and A.Dummy directly, instead of calling the abstract method that had both generic and non-generic implementations.
Noticed while working on #1035.
Incidentally supports #544.

Use test-specific creation methods instead of A.Fake/A.Dummy

---

README.md

I can only imagine that this worked at one time, but GitHub's markdown rendering has changed in the meantime.

fix markdown for readme footer

---

appveyor.yml

We should really specify this in config, rather than relying on the UI.

specify VS2015 in config

---

src/FakeItEasy/FakeObjectCallExtensions.cs
tests/FakeItEasy.Specs/ObjectCallSpecs.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/FakeObjectCallExtensionsTests.cs

Deprecate FakeObjectCallExtensions.Write and .WriteToConsole

---

src/FakeItEasy/Fake.of.T.cs

I introduced the warning in #1041.

Suppress CA1006 warning on Fake<T>.CallsToSet

---

src/FakeItEasy.Analyzer.CSharp/Resources.Designer.cs
src/FakeItEasy.Analyzer.CSharp/Resources.resx
src/FakeItEasy.Analyzer.VisualBasic/Resources.Designer.cs
src/FakeItEasy.Analyzer.VisualBasic/Resources.resx
src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Core/DefaultExceptionThrower.cs
src/FakeItEasy/Core/DefaultFixtureInitializer.cs
src/FakeItEasy/Creation/CastleDynamicProxy/DynamicProxyMessages.cs
src/FakeItEasy/Creation/ProxyOptions.cs
src/FakeItEasy/DummyFactory.cs
src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/FakeOptionsBuilder.cs
src/FakeItEasy/IoC/DictionaryContainer.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/NonVirtualSetupAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/NonOverridableSetupAnalyzerTests.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Specs/ConfiguringPropertySetterSpecs.cs
tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/SelfInitializedFakesSpecs.cs
tests/FakeItEasy.Tests/Core/DefaultExceptionThrowerTests.cs
tests/FakeItEasy.Tests/Core/DefaultFakeManagerAccessorTests.cs
tests/FakeItEasy.Tests/Core/DefaultFixtureInitializerTests.cs
tests/FakeItEasy.Tests/Core/DummyFactoryTests.cs
tests/FakeItEasy.Tests/Creation/CastleDynamicProxy/CastleDynamicProxyGeneratorTests.cs
tests/FakeItEasy.Tests/FakeOptionsBuilderTests.cs
tests/FakeItEasy.Tests/NullGuardedAssertion.cs
tests/FakeItEasy.Tests/NullGuardedAssertionTests.cs

Fixes #1011:
- double quotes for string values
- no quotes when values cannot have spaces
- single quotes otherwise

Rationalize use of quotation marks

---

src/FakeItEasy/A.cs
src/FakeItEasy/Core/InterceptedFakeObjectCallExtensions.cs
src/FakeItEasy/Fake.of.T.cs
src/FakeItEasy/Sdk/Create.cs

Supports #769. Fixes a bug I introduced in #1052.

Make IFakeAndDummyManager properties, not fields

---

CONTRIBUTING.md
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/FakeOptionsBuilder.cs
tests/FakeItEasy.IntegrationTests/DummyTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintTestBase.of.T.cs
tests/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
tests/FakeItEasy.Tests/TestHelpers/UsingCultureAttribute.cs

Cleans up style warnings revealed after conversion to StyleCop.Analyzers in #1090.

Fix 'suppress' style warnings

---

tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs

to suppress warnings when trying to load types from `DynamicProxyGenAssembly2`.
Fixes #1093 
Supersedes #1097

Capture output of integration tests

---

src/FakeItEasy/Core/TypeCatalogue.cs
tests/FakeItEasy.IntegrationTests/ExternalAssemblyGenerator.cs
tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs

Fixes #1092 
The warning message looks like this:
```
Warning: FakeItEasy failed to get some types from assembly 'FakeItEasy.ExtensionPoints.External, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' while scanning for extension points. Some IArgumentValueFormatters, IDummyFactories, and IFakeOptionsBuilders in that assembly might not be available.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
1 type(s) were not loaded for the following reasons:
- System.IO.FileNotFoundException: Could not load file or assembly 'FakeItEasy.ExtensionPoints.ExternalDependency, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file …
```

Handle case where some types can't be loaded from external assembly

---

appveyor.yml

Because if we don't, it's sometimes hard to find out why the build fails.

Publish artifacts even when the build fails

---

docs/argument-constraints.md

Fixes #1104.
I fixed up a few other typos while I was here.

Fix some typos in the Argument Constraints docs

---

FakeItEasy.sln
build.cmd
build.csx
packages.config

The solution requires VS2017 anyway, so we shouldn't rely on VS2015 in any way.
Fixes #1113

Fix build when VS2015 is not installed

---

.gitignore
FakeItEasy.sln
build.csx
src/FakeItEasy.nuspec.template

Fixes #1133 
- FakeItEasy.nuspec is renamed to FakeItEasy.nuspec.template, with no dependencies specified
- The build script generates FakeItEasy.nuspec from the template, using FakeItEasy.csproj to fill the dependencies
- The dependencies are located using the `Condition="'$(TargetFramework)' == '{tfm}'"` attribute. _This is a bit crude, and will break if we use more complex conditions_
- Build-only dependencies are identified by the presence of the `<PrivateAssets>` element. _This is also an oversimplification, because `<PrivateAssets>` can have values other than `all`, but it works fine with the current bits._

Generate nuspec dependencies from project file

---

src/FakeItEasy/Core/FakeAsserter.cs
src/FakeItEasy/Core/IFakeAsserter.cs
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs
tests/FakeItEasy.Tests/Core/FakeAsserterTests.cs

Fixes #1159
A simpler fix would have been to just call `.ToList()` on the calls in the `FakeAsserter` constructor, but it would have created unnecessary copies of the call list, which could possibly be large.

Fix race condition in call assertion

---

GitVersion.yml

Otherwise the package comes out as FakeItEasy.4.0.0-beta0001.

Use 3 digits in version pre-release number

---

appveyor.yml
deploy.ps1

- only when building a tag
- will attach to release with same name as tag
- errors out if no such release is found
- attaches all the nupkgs
Fixes #1171.

Automatically attach artifacts to GitHub Release

---

deploy.ps1

Supports #1171.
You can see the failure in [AppVeyor build 390](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/390#L666).

Fix nuget server name

---

src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/EnumerableExtensions.cs
src/FakeItEasy/OutputWriterExtensions.cs
src/FakeItEasy/StringBuilderOutputWriter.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/IsSameSequenceAsWithLongSequenceTests.cs
tests/FakeItEasy.Tests/Core/ArgumentValueFormatterTests.cs

Fixes #1193 
It seems to work pretty well, but I'm worried about one thing: when formatting argument values in the list of calls, what should happen for nested collections? My current implementation will recursively format the collections, but it will probably hurt the readability of the output...
Also, I noticed a few inconsistencies:
- When we write constraint descriptions, we use `IOutputWriter.WriteArgumentValue` to format values, but when we write the list of calls, we use `ArgumentValueFormatter`.
- Anyway, shouldn't `DefaultOutputWriter.WriteArgumentValue` use `ArgumentValueFormatter`, in order to take custom argument value formatters into account?
- Null values are formatted inconsistently between `DefaultOutputWriter` (`NULL`) and `ArgumentValueFormatter` (`<NULL>`).

Better description for IsSameSequenceAs constraint

---

Directory.Build.props
FakeItEasy.sln
samples/Directory.Build.props
samples/FakeItEasy.Examples.VB/FakeItEasy.Examples.VB.vbproj
samples/FakeItEasy.Examples/FakeItEasy.Examples.csproj
src/Directory.Build.props
src/FakeItEasy.Analyzer/Directory.Build.props
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.VisualBasic.csproj
src/FakeItEasy/FakeItEasy.csproj
tests/Directory.Build.props
tests/FakeItEasy.Analyzer.CSharp.Tests/FakeItEasy.Analyzer.CSharp.Tests.csproj
tests/FakeItEasy.Analyzer.VisualBasic.Tests/FakeItEasy.Analyzer.VisualBasic.Tests.csproj
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests.Approval/FakeItEasy.Tests.Approval.csproj
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Using `Directory.Build.props` files as explained [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build), we can factorize a lot of project properties and package references.
Benefits:
- even smaller project files
- no repetition of common properties and package references
- dependencies versions are specified in one place, which ensures consistency
Drawbacks:
- Visual Studio project properties designer doesn't seem to handle inherited properties very well... it can read them just fine, but editing them doesn't work (no error, but the changes are not persisted). Not really worse than before, since it already didn't support multiple target frameworks...
- Updating a package in NuGet package manager doesn't modify the Directory.Build.props file, but the csproj …

Use Directory.Build.props for common build properties

---

docs/argument-constraints.md
src/FakeItEasy/Configuration/IArgumentValidationConfiguration.cs

Document that WhenArgumentsMatch ignores inline argument constraints

---

src/FakeItEasy/Core/DefaultArgumentConstraintManager.cs
src/FakeItEasy/Core/ITypedArgumentConstraint.cs
src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/Expressions/ArgumentConstraints/AggregateArgumentConstraint.cs
src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Fixes #1237 
The 3rd commit is a simplification. I realized that only `MatchesConstraint` could be created by the argument constraint trap, so we don't need to introduce a `Type` property for other types of constraint.

Detect wrong-typed constraints

---

tests/FakeItEasy.Specs/CreationSpecs.cs

See [build warning](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/533-egvkdrfx#L183).
I missed it when it was introduced in #1259.

Remove blank line from beginning of file

---

src/FakeItEasy/Configuration/IRepeatConfiguration.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt

As mentioned in https://github.com/FakeItEasy/FakeItEasy/pull/1293/files#r165813185
The first commit
- fixes the inconsistency in the parameter name between doc comments and actual signature
- changes the wording of the interface and method summaries
The second commits actually renames the parameter to `numberOfTimes`. I did it as a separate commit, because it's a breaking change. I think we could still do it, because the chances that it will actually impact anyone are extremely low. If you disagree, I'll remove the commit.
Contributes to #1292.

Change documentation comments for IRepeatConfiguration

---

Directory.Build.props
samples/FakeItEasy.Examples.ruleset
src/FakeItEasy.Analyzer/ArgumentConstraintTypeMismatchAnalyzer.cs
src/FakeItEasy.ruleset
tests/FakeItEasy.Analyzer.CSharp.Tests/NonVirtualSetupAnalyzerTests.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Tests.ruleset

I wanted to use a `!` with pattern matching as part of my work on #1297.
StyleCop.Analyzers couldn't handle it, thinking that 
```c#
if (!(context.Node is InvocationExpressionSyntax call))
```
had too many parentheses. I noticed the bug was fixed in 1.1.0-beta006, so thought, "why not upgrade?".

Use StyleCop.Analyzers 1.1.0-beta006

---

src/FakeItEasy.Analyzer/Directory.Build.props
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.ruleset

I missed these warnings when I suppressed SA0001 for tests and samples.

Squelch SA0001 warning for Analyzer

---

CONTRIBUTING.md

When git stashing link is clicked, NET::ERR_CERT_DATE_INVALID warning is raised by Chrome browser. It appears that SSL certificate expired on 18.10.2016. This commit changes the link to the current ProGit's stashing page.

Changed ProGit book link with expired certificate

---

src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Expressions/CallConstraintDescriber.cs
src/FakeItEasy/Expressions/CallExpressionParser.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallMatcherTests.cs

Don't always use ExpressionCallMatcher to describe call constraints

---

src/FakeItEasy/Configuration/AnyCallCallRule.cs
src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Expressions/CallConstraintDescriber.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/Expressions/ExpressionCallRule.cs
tests/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallMatcherTests.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallRuleTests.cs

When fixing #684, I noticed that we use output writers to make strings that we pass to output writers that we use to make strings…
This will take out at least one place where we go writer → string → writer.
It's just a peeve of mine, and if we don't want to bother, I understand.

Write call constraint to writer instead of converting to string

---

src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Expressions/CallConstraintDescriber.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallMatcherTests.cs

This is embarrassing. After #1313, CAllConstraintDescriber no longer needed to have instances.
Why not make it static?

Make CallConstraintDescriber static

---

docs/assertion.md

Correct a small typo in the documentation for assertion with mutable arguments.

tiny typo fix in assertion.md

---

src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs

Fixes #1348.
Works around the particular failure reported in #1345.

Protect argument resolution failure

---

tools/build.csx
tools/packages.config

- [Bullseye](https://github.com/adamralph/bullseye) replaces simple-targets-csx (it's a regular binary package instead of scripts, so can optionally be used in a [regular .NET project](https://github.com/xbehave/xbehave.net/blob/6d798877b4b891ce95ea8f2c5f9bee3d56a26bae/targets/Program.cs#L8)).
- [SimpleExec](https://github.com/adamralph/simple-exec/) wraps up command invocation, so removes the need to include local helpers

switch to Bullseye and SimpleExec

---

tools/build.csx

If vswhere returns an empty line, the method returns an empty string instead of throwing the exception.

fix GetVSLocation

---

docs/what-can-be-faked.md
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/InParametersSpecs.cs

Support in parameters in non-generic classes under .NET Core

---

tools/build.csx
tools/packages.config

Contains a minor fix concerning console output for targets with a `null` action (an unusual thing to do). You shouldn't notice any difference.

update to Bullseye 1.0.0-rc.5

---

src/FakeItEasy/Configuration/AnyCallCallRule.cs
src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/Core/CallCountConstraint.cs
src/FakeItEasy/Core/DefaultArgumentConstraintManager.cs
src/FakeItEasy/Core/DynamicDummyFactory.cs
src/FakeItEasy/Core/DynamicOptionsBuilder.cs
src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/UserCallbackException.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.ruleset
tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
tests/FakeItEasy.Specs/UserCallbackExceptionSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt

Fixes #1341
Here's a (hopefully) complete list of APIs where we execute user-provided callbacks:
- Fake creation APIs
- Call specification APIs
- Call configuration APIs
- Call assertion APIs
- Extension points

Handle exceptions in user callbacks

---

tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs

As noted in https://github.com/FakeItEasy/FakeItEasy/pull/1410#issuecomment-413938393, there is a race condition in a couple of tests that count the number of times failing constructors are called. This should ensure we run those tests serially rather than concurrently.

Serialize dummy/fake creation in specs that count constructor calls

---

tools/FakeItEasy.Build/Program.cs

avoid unecessary MSBuild finding

---

FakeItEasy.sln

So that we can edit them in Visual Studio and VSCode (technically, it was already possible to edit them in VSCode, but OmniSharp doesn't take the projects into account if they're not part of the solution, so no intellisense or analysis)
I disabled build for these projects in the solution configuration so that running `FakeItEasy.Build` doesn't attempt to rebuild `FakeItEasy.Build` 😉

Add FakeItEasy.Build and FakeItEasy.PrepareRelease projects to solution

---

how_to_build.md
tools/FakeItEasy.Build/FakeItEasy.Build.csproj
tools/FakeItEasy.Build/Program.cs

As discussed with @adamralph, not sure where/when it was.
We no longer need to call MSBuild explicitly, so we don't need VSWhere anymore.

Drop MSBuild, use dotnet build instead

---

tests/Directory.Build.props
tools/FakeItEasy.Build/Program.cs

Upgrade xunit to 2.4.0, switch to dotnet test

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj

So this is actually the thing I was trying to fix which, when checking it didn't break anything, led me to raise https://github.com/FakeItEasy/FakeItEasy/pull/1442.
I guess this package reference became redundant some time ago.

remove xunit console

---

.editorconfig
CONTRIBUTING.md
README.md
docs/argument-constraints.md
docs/creating-fakes.md
docs/external-resources.md
docs/what-can-be-faked.md
docs/why-was-fakeiteasy-created.md
src/FakeItEasy.Analyzer.nuspec
src/FakeItEasy.Dictionary.xml
src/FakeItEasy/Core/FakeCallEqualityComparer.cs
src/FakeItEasy/IHideObjectMembers.cs
tests/FakeItEasy.Dictionary.Tests.xml

I noticed that the Markdown preview in VSCode didn't load the FakeItEasy logo because it was a non secure URL. So while I was at it, I updated all links to use https. (except sourcebrowser.io, which doesn't support https)

Update links to use https in README.md

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj

Exactly twice as fast with the new `--parallel` option! You may want to think twice before using it for CI though, since the console output from many targets get interleaved, and there's not much that can be done about that. I've been using it to speed up local builds.

upgrade to Bullseye 2.0.0 RC2

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj

Looking for feedback on this version. The main change is that a specific colour palette is chosen depending on which CI system is detected. Currently Appveyor, Travis CI, and TeamCity are supported.
For reference, this is how the output looks in a local console:
And these are the console colours available on Appveyor:

switch to Bullseye 2.1.0 beta 1

---

src/FakeItEasy/Expressions/ExpressionCallMatcher.cs

Connects to #1470.
Most of the time, we have no out or ref parameters to fetch values from, but we're LINQing and creating a list all the time. Even when we do have out and ref parameters, it's not the cheapest way to construct the list.

Stop using Linq in GetOutAndRefParametersValueProducer

---

tests/Directory.Build.props

Just to ensure no xunit/xbehave related problems arise through using an older version. BTW - [xunit 2.4.1 is coming soon](https://twitter.com/xunit/status/1055916132714958848)...

upgrade Microsoft.NET.Test.Sdk to 15.9.0

---

src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs

Connects to #1470.
Checking to see if a parameter is a params array is expensive. Let's at least not do it unless the parameter is an array. Also, let's check smarter.

Optimize IsParamArrayExpression

---

src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Configuration/PropertySetterConfiguration.cs
src/FakeItEasy/Expressions/CallExpressionParser.cs
src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/Expressions/ParsedCallExpression.cs

Connects to #1470.
I noticed two hotspots in the code afetr the latest optimization:
1. zipping and otherwise transforming constraint argument expressions, and
2. determining whether a method was static when checking the validity of the argument constraints (basically do we have nested `A._`s and the like.
I didn't save my dotTrace output from the first change, only the second. It does improve the case when we're using a built-in extension such as `Is.EqualTo` or the like, but may have a (much smaller) drag when we're using a user-supplied extension method. I show both scenarios here, in that order:
I do have the benchmarks for what's in develop, after the first commit ("no-zip") and after the second commit. Now with error bars!

Improve call configuration for methods with parameters

---

src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs
src/FakeItEasy/Creation/IProxyOptions.cs
src/FakeItEasy/Creation/ProxyOptions.cs
tests/FakeItEasy.Tests/Creation/CastleDynamicProxy/CastleDynamicProxyGeneratorTests.cs

Connects to #1489.
Comparing develop (4.10.0-alpha068  / 19d298621bbe60c8f456a58ae92e285da31bc708) to this PR (4.10.0-do-not-linq-addit001) results in
|                                            Method |                         Job |      Mean |     Error |    StdDev | Ratio |
|-------------------------------------------------- |---------------------------- |----------:|----------:|----------:|------:|
| A.Fake&lt;SimpleClass&gt;(o =&gt; o.Implements&lt;IFake&gt;()) |             4.10.0-alpha068 | 10.481 us | 0.1211 us | 0.0801 us |  1.00 |
| A.Fake&lt;SimpleClass&gt;(o =&gt; o.Implements&lt;IFake&gt;()) | 4.10.0-do-not-linq-addit001 | 10.310 us | 0.1566 us | 0.1036 us |  0.98 |
|                             A.Fake&lt;SimpleClass&gt;() |             4.10.0-alpha068 |  9.737 us | 0.1732 …

Avoid LINQ when constructing list of all proxy interfaces

---

src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
tests/FakeItEasy.Tests/Creation/CastleDynamicProxy/CastleDynamicProxyGeneratorTests.cs

Connects to #1489.
We do a lot of double-checking of faked types and guarding against constructor arguments being present when we don't need to. If we have a dedicated method for faking interfaces (which I still hope is the most common case), we can save some work.
I took it in two steps. The second one just realizes that we don't need a common interface on `DelegateCreationStrategy` and `DefaultCreationStrategy` and that we can then remove the LINQing over the list of them. This actually improves configuration and verification performance a little bit, as it's cheaper to see who's responsible for intercepting a method.
My version of the BenchmarkMockNet tests:
|          Method |                         Job |                        NuGetReferences |      Mean |     Error |    StdDev | …

Streamline faked interface creation

---

src/FakeItEasy/Expressions/ExpressionCallMatcher.cs

|     Method |                       Job |      Mean |     Error |    StdDev | Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|----------- |-------------------------- |----------:|----------:|----------:|------:|--------:|------------:|------------:|------------:|--------------------:|
|     Verify |           4.10.0-alpha094 | 22.444 us | 0.2249 us | 0.2104 us |  1.00 |    0.00 |      1.8500 |      0.0200 |      0.0100 |             5.83 KB |
|     Verify | 4.10.0-optimize-verify001 | 21.444 us | 0.2543 us | 0.2379 us |  0.96 |    0.02 |      1.8200 |      0.0200 |      0.0100 |             5.73 KB |
| VerifyOnly |           4.10.0-alpha094 |  6.459 us | 0.1397 us | 0.1307 us |  1.00 |    0.00 |      0.6400 |           - |           - |             1.99 …

Stop using Zip to check argument constraints

---

FakeItEasy.sln
GitVersion.yml
src/CommonAssemblyInfo.cs
src/Directory.Build.props
src/FakeItEasy.Analyzer.CSharp/FakeItEasy.Analyzer.CSharp.csproj
src/FakeItEasy.Analyzer.Shared/Properties/AssemblyInfo.cs
src/FakeItEasy.Analyzer.VisualBasic/FakeItEasy.Analyzer.VisualBasic.csproj
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/Properties/AssemblyInfo.cs
tools/FakeItEasy.Build/FakeItEasy.Build.csproj
tools/FakeItEasy.Build/Program.cs

I see you dropped the analyser meta-package, which made this easy. 🙂

switch to MinVer

---

tools/FakeItEasy.Build/Program.cs

Restore nupkgs to artifacts/output

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj
tools/FakeItEasy.Build/Program.cs

Main features:
Returns after a two second delay while three entries are written to the OS event logs.
Returns immediately with nothing written to the OS event logs.

update Bullseye to 2.3.0-beta.3

---

tools/Directory.Build.props
tools/FakeItEasy.Build/Program.cs

Since each target is a one-liner which calls SimpleExec, the stack traces are useless. This change this:
to this:

show messages only for build exceptions

---

src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
src/FakeItEasy/ExceptionMessages.cs
tests/FakeItEasy.Specs/FakingDelegates.cs
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs

Warn that delegates can't call base method at configuration time

---

src/FakeItEasy/Configuration/BuildableCallRule.cs
tests/FakeItEasy.Specs/UserCallbackExceptionSpecs.cs

Specifically to include
* UserCallbackException is thrown when another Exception is expected (#1543)

Merge hotfix 4.9.2

---

docs/invoking-custom-code.md
tests/FakeItEasy.Specs/ConfigurationSpecs.cs

While I was looking at #1496, I noticed that the documentation for `Invokes` said that the return value would be `null` or `default` unless `Returns` was used to change it, but this is not so.

Correct documentation on return value when Invokes is used

---

README.md

[sourcebrowser.io](http://sourcebrowser.io/) appears to be dead, and has been in this state for a while. No reason to keep the badge.

Remove Source Browser badge and link

---

tools/Directory.Build.props
tools/FakeItEasy.Build/FakeItEasy.Build.csproj

- Bullseye from 2.3.0 to 2.4.0-beta.1
- SimpleExec from 6.0.0-beta.1 to 6.0.0
Contains (among other things) adamralph/bullseye#168.

Update Bullseye to 2.4.0-beta.1 and SimpleExec to 6.0.0

---

tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs

As @thomaslevesque noticed, running `DefinedFakeOptionsBuilderWrapping` under net461 with a debug build failed.
The spec created a fake object before all services were registered.

Stop creating a fake in WrapsAValidObjectOptionsBuilder static constructor

---

appveyor.yml

Fixes #1609
I added the environment variables on AppVeyor, and removed the VERSION_SUFFIX variables which wasn't used anywhere.

Remove environment variables from appveyor.yml

---

tools/Directory.Build.props
tools/FakeItEasy.Build/FakeItEasy.Build.csproj

- [Bullseye 3.0.0-beta.3](https://github.com/adamralph/bullseye/issues?q=milestone%3A3.0.0+label%3Aenhancement)
- [SimpleExec 6.1.0-beta.1](https://github.com/adamralph/simple-exec/issues?q=label%3Aenhancement+milestone%3A6.1.0)
I'd love to get your feedback on these changes. They are mainly cosmetic: a bunch of logging tweaks. In the case of Bullseye, a few of the changes are marked `breaking` but purely because the logging was previously done to stdout, so theoretically the output could have been being piped to another program and parsed. All logging is done to stderr now.

update build tools

---

src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Expressions/ExpressionCallRule.cs
tests/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs

Came out of the nullability work for #1613. I found an opportunity to remove more  nullability warnings without using the C# 8 language features. While I was looking, I noticed that the `OutAndRefParametersValueProducer` is only ever gotten from outside the class by unit tests that are covered in the specs.
I was going to remove the getter, but then we'd have a set-only property, which StyleCop would complain about.
And it seems to me that if we're going to have annoying checks and chances of failure, that code would fit better on a method than a property, so I swapped their roles.
I'll be sending another pull request to pre-reduce some nullability warnings, including the unset `OutAndRefParametersValueProducer`.

Protect out and ref parameters value producer

---

src/FakeItEasy/Configuration/AnyCallCallRule.cs
src/FakeItEasy/Configuration/AnyCallConfiguration.cs
tests/FakeItEasy.Tests/Configuration/AnyCallConfigurationTests.cs

Again, found while I was investigating #1613.
We have some properties that don't need to be exposed (and duplicated tests). Removing them and simplifying the implementation will eventually avoid some nullability warnings, since `applicableToMembersWithReturnType` will never be null now.

Simplify type checking in AnyCallRule

---

appveyor.yml
how_to_build.md
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Run tests against netcoreapp3.0

---

tools/FakeItEasy.Deploy/FakeItEasy.Deploy.csproj
tools/FakeItEasy.Deploy/Program.cs
tools/FakeItEasy.PrepareRelease/FakeItEasy.PrepareRelease.csproj
tools/FakeItEasy.PrepareRelease/Program.cs
tools/ReleaseHelpers.cs

Add 'released as part of' notes to issues when releasing

---

src/FakeItEasy/OutputWriterExtensions.cs

We never set the value to `true`, and probably won't start.

Remove option to skip formatting of argument values

---

src/FakeItEasy/Creation/FakeAndDummyManager.cs
src/FakeItEasy/Creation/FakeOptions.cs
src/FakeItEasy/Creation/IFakeOptions.of.T.cs
src/FakeItEasy/FakeOptionsBuilder.cs
src/FakeItEasy/FakeOptionsExtensions.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt

Could've been done as part of #1465, but I didn't think of it.
In addition to just providing a better view for the public API, this change removes 6 nullability warnings:
```
Creation\FakeOptions.cs(20,68): warning CS8604: Possible null reference argument for parameter 'obj' in 'void Action<object>.Invoke(object obj)'. 
Creation\FakeOptions.cs(84,31): warning CS8604: Possible null reference argument for parameter 'argument' in 'void Guard.AgainstNull(object argument, string argumentName)'. 
Creation\FakeOptions.cs(85,60): warning CS8604: Possible null reference argument for parameter 'fakedObject' in 'void FakeOptions<T>.ConfigureFakeToWrap(object fakedObject, object wrappedObject)'. 
Creation\FakeOptions.cs(85,66): warning CS8604: Possible null reference argument for parameter …
```

Limit typeparams for Fake options and builder classes

---

src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/CallbackConfigurationExtensions.cs
src/FakeItEasy/CompletedFakeObjectCallExtensions.cs
src/FakeItEasy/Configuration/ArgumentCollection.cs
src/FakeItEasy/Configuration/PropertySetterConfiguration.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Configuration/UnorderedCallAssertion.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/Raise.of.TEventArgs.cs
src/FakeItEasy/Creation/FakeOptions.cs
src/FakeItEasy/ExceptionThrowerConfigurationExtensions.cs
src/FakeItEasy/OutputWriterExtensions.cs
src/FakeItEasy/ReturnValueConfigurationExtensions.StronglyTyped.cs
src/FakeItEasy/ReturnValueConfigurationExtensions.StronglyTyped.tt

Some public methods that will not allow null argument values lack null checks.
Perhaps some have arguably too many.

Add and remove null parameter checks

---

how_to_build.md
tools/FakeItEasy.Build/Program.cs

Add targets to create and manage FakeItEasy.user.props

---

tools/FakeItEasy.Build/Program.cs

We do when building, so why not for the other targets?

Suppress logo when testing and packing

---

Directory.Build.props
src/FakeItEasy/A.cs
src/FakeItEasy/Core/FakeManager.EventRule.cs
src/FakeItEasy/Core/Raise.of.TEventArgs.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidator.cs
src/FakeItEasy/Creation/CreationResult.cs
src/FakeItEasy/ExpressionExtensions.cs
src/FakeItEasy/IHideObjectMembers.cs
src/FakeItEasy/Times.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/CodeFixVerifier.Helper.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/DiagnosticVerifier.Helper.cs
tests/FakeItEasy.IntegrationTests/ExternalAssemblyGenerator.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Specs/DummyFactorySpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/stylecop.json
tests/FakeItEasy.Tests.Approval/ApiApproval.cs
tests/FakeItEasy.Tests/ArgumentValidationConfigurationExtensionsTests.cs
tests/FakeItEasy.Tests/Core/DefaultFakeObjectCallFormatterTests.cs
tests/FakeItEasy.Tests/ExceptionContractTests.cs

Because it's nice to upgrade.
Also because the new rules understand constructs like 
`var eventInfo = GetEvent(fakeObjectCall.Method)!`, which I'd longed for while working on the nullability branch.

Upgrade StyleCop.Analyzers to 1.2.0-beta.113

---

src/FakeItEasy/Core/ArgumentValueFormatter.cs
tests/FakeItEasy.Specs/CallDescriptionsInAssertionSpecs.cs
tests/FakeItEasy.Specs/UserCallbackExceptionSpecs.cs

Use alternate when argument value formatter throws or returns null

---

docs/analyzer.md
mkdocs.yml

Contributes to #1735. Corrects an error introduced in #1741.

Restore fancy docs table of contents structure

---

src/Directory.Build.props

According to https://github.com/adamralph/minver/pull/347, if we don't, we'll have problems building with dotnet sdk 3.1.300+

Update MinVer to 2.3.0

---

docs/default-fake-behavior.md
src/FakeItEasy/Core/FakeManager.ObjectMemberRule.cs
src/FakeItEasy/Core/MethodInfoManager.cs
src/FakeItEasy/MethodBaseExtensions.cs
src/FakeItEasy/MethodInfoExtensions.cs
tests/FakeItEasy.Specs/ObjectMembersSpecs.cs

Fixes #1777
To be merged after 6.1.0 release
The last commit is optional, but I thought it made sense. I needed a `MethodInfo` to get access to `GetBaseDefinition`, and I realized that the methods in `MethodBaseExtensions` were *always* called on `MethodInfo`, so I changed their signature and renamed the class. I'm happy to rollback if you have an objection.

Apply Object member rules to overridden members

---

src/FakeItEasy/Core/TypeCatalogue.cs
src/FakeItEasy/RootModule.cs
src/FakeItEasy/TypeExtensions.cs
tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs
tests/FakeItEasy.Tests/TypeExtensionsTests.cs

- Exclude FIE Assembly from TypeCatalogue
- Adjust CanBeInstantiatedAs to include checking for a public no-arg constructor.
All the tests were passing on .NET Core, I had issues w/ getting the full framework to run on my machine due to missing very old framework versions.

Prevent TypeCatalogueInstanceProvider from throwing a first chance MissingMethodException instantiating DefaultEnumerableValueFormatter

---

tests/FakeItEasy.Tests.TestHelpers/FakeItEasy.Tests.TestHelpers.csproj
tests/FakeItEasy.Tests.TestHelpers/UsingCultureAttribute.cs
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Continues #1801 a bit, as suggested by @thomaslevesque  in https://github.com/FakeItEasy/FakeItEasy/pull/1801#issuecomment-731448162

Remove compilation constant FEATURE_THREAD_CURRENTCULTURE

---

docs/argument-constraints.md
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net5.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/EqualToWithComparerConstraintTests.cs

Hi, we have started using FakeItEasy in our main code base and while migrating from RhinoMocks I missed a method argument constraint where you can use EqualTo with custom comparer. Originaly we were using `That.Matches(Predicate)` constraint, then we have created our own extension method for that to be able to pass equality comparer and I thought it would be nice if it was part of the framework so I created this PR if you are interested.
Cheers 🎆

Add EqualTo overload with equality comparer

---

src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs
src/FakeItEasy/Creation/CastleDynamicProxy/DynamicProxyMessages.cs
src/FakeItEasy/Creation/FakeAndDummyManager.cs
src/FakeItEasy/ExceptionMessages.cs
tests/FakeItEasy.Specs/CreationSpecs.cs

Throw FakeCreationException when using Sdk.Create to fake a value type with fake creation options

---

docs/dummies.md

I used the Github UI to make this change, and it looks like it created the branch on this repo instead of my fork... sorry about that.

Remove extraneous text in dummies doc page

---

tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs

Completely unrelated to other ongoing work. I noticed that this test was skipped for all frameworks, but it was supposed to run for net461. This was due to an incorrect TFM in a MSBuild condition.
In addition, just re-enabling the test made it fail, because the exception message no longer contains the path to the assembly, it just contains its full assembly name.

Re-enable and fix integration test in net461

---

.editorconfig
docs/raising-events.md
docs/specifying-a-call-to-configure.md
docs/strict-fakes.md
src/FakeItEasy/A.cs
src/FakeItEasy/Configuration/AnyCallConfigurationWithNoReturnTypeSpecifiedExtensions.cs
src/FakeItEasy/Configuration/IManageEventConfiguration.cs
src/FakeItEasy/Core/EventCall.cs
src/FakeItEasy/Core/EventCallHandler.cs
src/FakeItEasy/Core/FakeManager.EventRule.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/StrictFakeRule.cs
src/FakeItEasy/EventAction.cs
src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/Fake.of.T.cs
src/FakeItEasy/Manage.cs
src/FakeItEasy/StrictFakeOptions.cs
tests/FakeItEasy.Specs/EventActionSpecs.cs
tests/FakeItEasy.Specs/ManageEventsSpecs.cs
tests/FakeItEasy.Specs/StrictFakeSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net5.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt

Fixes #1841 
This PR contains 3 separate (but related) features. We might keep all of them, or none...
07e9d4a4: Update .editorconfig to add C# style rules. Not related to the rest of this PR, but I was getting tired of fighting Visual Studio defaults... I can move it to a separate PR if you prefer.
f4a2950b, 84d77c8d, 297ea48e, 27d2d1cf : API to simplify configuration of event accessors
6c6758cc, df35a992, 6651ce52, b8f82063 : API to enable default event behavior on a fake
a3d91e0c, 13935d3e, d560a346: add StrictFakeOptions.ManageEvents
EDIT: added two more commits:
- 3b4b1e23: add a more detailed exception message when fake accessors are called on a strict fake
- 6bed3ed4: use a single EventCallHandler per fake so that multiple calls to `Manage.Event` don't cause unexpected behavior. …

Event API improvements

---

src/FakeItEasy/Core/FakeManager.ObjectMemberRule.cs
src/FakeItEasy/Core/InterceptedFakeObjectCallExtensions.cs
src/FakeItEasy/Core/StrictFakeRule.cs
src/FakeItEasy/Core/WrappedObjectRule.cs
src/FakeItEasy/MethodInfoExtensions.cs
src/FakeItEasy/ObjectMethod.cs

Connects to #1848.
I hesitate to say fix, but it addresses at least one area of slowness identified there.
Has this affect on runtimes (6.1.0 is the build before we changed a lot of method comparisons to see if a call had the same base method as a given method).
Method |             Job |      Mean |     Error |    StdDev | Ratio | RatioSD |
------- |---------------- |----------:|----------:|----------:|------:|--------:|
Equals |           6.1.0 |  4.738 us | 0.3711 us | 0.2208 us |  1.00 |    0.00 |
Equals |           7.1.0 | 11.110 us | 0.6914 us | 0.4115 us |  2.35 |    0.14 |
Equals | 7.1.1-alpha.0.5 |  4.340 us | 0.3255 us | 0.2153 us |  0.91 |    0.08 |
and
Method                 |             Job |     Mean |     Error |    StdDev | Ratio | RatioSD |
----------------------- …

Optimize method comparison

---

docs/creating-fakes.md

Inspired by #1854, where @Bludator had noted that the original documentation was confusing.

Clarify use of WithArgumentsForConstructor expression

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj
tools/FakeItEasy.Build/Program.cs

- Use of top-level statements leads to reduced indentation (no namespace, no Program class, no Main method). Note that the code is now in the global namespace, but it doesn't matter in this case.
- Implicit usings leads to less using directives
- Converting  `Project` to a record makes it more concise
I'm not sure yet if I like it better or not...

Modernize build script by using C# 9 & 10 features

---

.gitignore
tools/FakeItEasy.Build/Program.cs

The `pack` target was failing because I have a space in the path to the repo. Adding double-quotes fixes the problem.

Fix pack build target to support spaces in path

---

docs/assertion.md

Fixed typo in method name in assertion documentation.

Fix typo in method name

---

docs/argument-constraints.md
docs/assertion.md
docs/assigning-out-and-ref-parameters.md
docs/creating-fakes.md
docs/how-to-fake-internal-types.md
docs/index.md
docs/ordered-assertions.md
docs/specifying-return-values.md
docs/why-was-fakeiteasy-created.md

While looking at the [Argument constraints](https://fakeiteasy.github.io/docs/7.3.1/argument-constraints/) page yesterday, I noticed that unlike many other pages, the subheadings don't appear in the page's table of contents:
I found it's because the page uses level 1 headings instead of level 2. Typically in mkdocs, the level 1 heading is used for the page title only. 
This PR attempts to remedy that. And also suppresses the table of contents on the main landing page, as it is not helpful:

Improve in-article tables of contents

---

mkdocs.yml
requirements.in
requirements.txt

Brings improved plugin versions, such as snippets, which will be used to add recipes to the docs.

Upgrade mkdocs-material to 9.1.3

---

FakeItEasy.sln
docs/Recipes/faking-http-client.md
mkdocs.yml
profiles/full.props
profiles/net45.props
profiles/net6.0.props
profiles/netcore2.1.props
profiles/netcore3.1.props
recipes/.editorconfig
recipes/Directory.Build.props
recipes/FakeItEasy.Recipes.CSharp/FakeItEasy.Recipes.CSharp.csproj
recipes/FakeItEasy.Recipes.CSharp/FakingHttpClient.cs
tools/FakeItEasy.Build/Program.cs

Adds runnable recipes (in form of tests) and includes those in a Recipe section of the documentation, by reading "snippets" right out of the executable recipe.
----
**Old description:**
Not baked yet, but a good starting point for discussion. In particular, we're going to at least want to decide whether we want these things called "case studies" or "recipes" or whatever. I picked one so I could have something to commit and push.
@thomaslevesque, everything's negotiable. For example, you might hate tone, approach of showing one way to work and then introducing the fakeable context, showing a "quicky" version of the test where we exercise the fake directly, anything. Don't hold back.
I also have ideas for hosting the code in this article (or others?) separately, similarly to the samples …

Add Faking HttpClient recipe

---

src/FakeItEasy/Configuration/ArgumentCollection.cs
tests/FakeItEasy.Specs/FakeSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net5.0.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.verified.txt

Make ArgumentCollection.GetArgumentNames return type IEnumerable<string?>

---

src/FakeItEasy/Core/DefaultFakeObjectCallFormatter.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/StrictFakeSpecs.cs

Follows from fix for #1920.
If a method has anonymous parameters, the description of a received call should use placeholder names just as we would for a call that is expected but not received.

Provide placeholder names for anonymous parameters in received call descriptions

---

src/FakeItEasy/MethodInfoExtensions.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Tests.TestHelpers.FSharp/FakeItEasy.Tests.TestHelpers.FSharp.fsproj
tests/FakeItEasy.Tests.TestHelpers.FSharp/IAmADelegateWithAnAnonymousParameter.fs
tests/FakeItEasy.Tests.TestHelpers.FSharp/postbuild.ps1
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj
tests/FakeItEasy.Tests/MethodInfoExtensionsTests.cs

Provides test coverage of the last 2 instances where we access parameter names, ensuring we behave somewhat sanely when the parameters have no names. Includes one minor change in how anonymous parameters are displayed, but we can only figure out how to exercise that via unit test. An "organic" use may not be possible.
Finishes work started in #1920, #1922, and #1924.

Ensure anonymous parameters are handled and displayed correctly in remaining cases

---

.github/workflows/ci.yml

It's been [removed](https://github.com/actions/runner-images/issues/7667) from Github Hosted worker images.

Install .NET Core 3.1 on Windows in CI

---

docs/doing-nothing.md

Correct anchor, but wrong page

Fix broken link in documentation

---

requirements.in
requirements.txt

Rolls up dependabot PRs #1946, #1957, and #1958.
Accomplished by running `pip-compile --upgrade requirements.in`.

Update docs dependencies for security

---

docs/argument-constraints.md
docs/custom-argument-equality.md
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/ArgumentEqualityComparer.cs
src/FakeItEasy/Core/ArgumentEqualityComparer.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/Expressions/ArgumentConstraints/NullArgumentConstraint.cs
src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
src/FakeItEasy/IArgumentEqualityComparer.cs
tests/FakeItEasy.Specs/ArgumentEqualityComparerSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net462.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net6.0.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.verified.txt
tests/FakeItEasy.Tests/Expressions/ArgumentConstraints/AggregateArgumentConstraintTests.cs
tests/FakeItEasy.Tests/Expressions/ArgumentConstraints/EqualityArgumentConstraintTests.cs

Choose equality comparer based on example type instead of parameter type

---

docs/argument-constraints.md
src/FakeItEasy/Core/ArgumentEqualityComparer.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
tests/FakeItEasy.IntegrationTests/CallMatchingTests.cs
tests/FakeItEasy.Specs/ArgumentEqualityComparerSpecs.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Tests/Expressions/ArgumentConstraints/AggregateArgumentConstraintTests.cs
tests/FakeItEasy.Tests/Expressions/ArgumentConstraints/EqualityArgumentConstraintTests.cs

Match enumerable arguments by comparing contents rather than via Equals

---

src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

```c#
A.CallTo(() => fake.Bar(An<int>.That.Matches(i => i % 2 == 0) +
An<int>.That.Matches(i => i % 2 == 1))).Returns(1));
```
yields
> FakeConfigurationException : Too many argument constraints specified. First superfluous constraint is <i => ((i % 2) == 1)>
but
```c#
A.CallTo(() => fake.Bar(A<int>.That.Matches(i => i % 2 == 0) +
A<int>.That.Matches(i => i % 2 == 1))).Returns(1));
```
yields
> InvalidOperationException : An argument constraint, such as That, Ignored, or _, cannot be nested in an argument.
The latter is technically more correct, since we're nesting the two constraints inside the `+` expression.
But we already have a test to detect multiple constraints, so we'd be better off with one that explicitly tests single nested constraints.

Nesting or compounding An-built constraints throws wrong exception

---

src/FakeItEasy/Core/FakeManager.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

When evaluating whether to apply a user rule the checks have the following order:
1. IsApplicableTo
2. HasNotBeenCalledSpecifiedNumberOfTimes
This commit changes that order to:
1. HasNotBeenCalledSpecifiedNumberOfTimes
2. IsApplicableTo
This means that we only evaluate argument matchers if the rule has not been called the specified number of times.

Evaluate argument matchers only if needed

---

src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs
src/FakeItEasy/Creation/CastleDynamicProxy/DynamicProxyMessages.cs
src/FakeItEasy/Creation/ProxyGeneratorResult.cs
tests/FakeItEasy.Specs/CreationSpecs.cs

Drop 'No constructor matches the passed arguments for constructor.'

---

src/FakeItEasy/Core/FakeManager.EventRule.cs
src/FakeItEasy/Core/FakeManager.cs

While investigating what needed to be saved for the `ResetToInitialConfiguration` feature, I realized we treated `EventRule` as a "special" stateful rule, but it doesn't actually need to be stateful, and can be shared among all fakes. What actually holds the state is the `EventCallHandler`, which is specific to each fake.
This PR is a small refactoring that makes `EventRule` just like the other shared rules.

Make EventRule shared

---

.github/workflows/publish-docs-preview.yml

[dawidd6/action-download-artifact](https://github.com/dawidd6/action-download-artifact) no longer works with actions/upload-artifact@v4.
Instead, find the latest successful workflow run for the PR's head commit, and download the artifact from that run, using actions/download-artifact@v4.
Also, add a final step so that the workflow fails if we didn't successfully publish the docs (currently it always passes due to the `continue-on-error` attribute)

Fix docs preview workflow

---

.github/workflows/publish-docs-preview.yml

Customize the name of the workflow run to `Publish docs preview for PR #xxx`.
Include the workflow run URL in the PR comment in case of error.

Improve docs preview workflow

---

docs/what-can-be-faked.md
tests/FakeItEasy.Specs/InParametersSpecs.cs

Acknowledge that we'll never be able to fake methods on generic types that have in parameters before .NET 6

---

docs/capturing-arguments.md
docs/doing-nothing.md
docs/specifying-a-call-to-configure.md

 Stress that methods must be fully configured to capture arguments

---

build.ps1

- added shebang
- converted line endings to LF (Windows doesn't care which it is)
- added execute mode bit

Make build.ps1 executable on Linux

---

docs/creating-fakes.md

The existing URL in the link to Moq seems to be for a gambling website, this update changes it to the github repo, which was the best online resource I could find for Moq.

Documentation fix: Update URL in link to Moq

---

src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/TypeExtensions.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj

As with #2019, an incomplete pull request at this time. Avoids touching the CreationResult code at all, as you suggested, @thomaslevesque.

Stop trying to create ByRef-like Dummies on TMFs lower than netstandard2.1

---

docs/how-to-fake-internal-types.md
mkdocs.yml

The first commit explains how to add `InternalsVisibleTo` to the project file.
The second explicitly shows the VB usage, because I was briefly confused by the phrase "the equivalent of the following". I can drop it if you don't like it.
Closes #2027

Update the docs to show how to specify InternalsVisibleTo in the project file

---

src/FakeItEasy/Core/EventCall.cs
tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Specs/EventSpecs.cs

Fix event subscription/unsubscription with null handler

---

src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidator.cs
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.IntegrationTests/ExceptionMessagesTests.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Specs/DefaultInterfaceMethodSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidatorTests.cs

Upgrade Castle.Core to 5.2.1, which introduces this support.
Fix the case of sealed default interface methods.
Reword the "non-virtual members can not be intercepted" message to also mentioned sealed members.
Fixes #1633

Add support for default interface methods
