FakeItEasy/FakeItEasy

Source/FakeItEasy-SL/FakeItEasy-SL.csproj
Source/FakeItEasy.Net35/FakeItEasy.Net35.csproj
Source/FakeItEasy.Tests/Configuration/ArgumentCollectionTests.cs
Source/FakeItEasy.Tests/Core/DefaultFakeObjectCallFormatterTests.cs
Source/FakeItEasy.Tests/Core/FakeCallEqualityComparerTests.cs
Source/FakeItEasy.Tests/Core/FakeManagerTests.cs
Source/FakeItEasy.Tests/Expressions/ExpressionCallMatcherTests.cs
Source/FakeItEasy.Tests/Expressions/ExpressionCallRuleTests.cs
Source/FakeItEasy.Tests/FakeCall.cs
Source/FakeItEasy.Tests/FakeItEasy.Tests.csproj
Source/FakeItEasy.Tests/FakeObjectCallExtensionsTests.cs
Source/FakeItEasy.Tests/SelfInitializedFakes/RecordingManagerTests.cs
Source/FakeItEasy.Tests/TestHelpers/ExpressionHelper.cs
Source/FakeItEasy/Configuration/ArgumentCollection.cs
Source/FakeItEasy/Configuration/IRepeatSpecification.cs
Source/FakeItEasy/Core/DelegateRaiser.cs
Source/FakeItEasy/Core/FakeManager.cs
Source/FakeItEasy/Core/IFakeObjectCall.cs
Source/FakeItEasy/Core/Raise.of.TEventArgs.cs
Source/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs
Source/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
Source/FakeItEasy/Expressions/ExpressionCallMatcher.cs
Source/FakeItEasy/FakeItEasy.csproj
Source/FakeItEasy/Repeated.cs

432 improve namespaces

---

Source/CommonAssemblyInfo.cs

set version to 1.25.2 for next release

---

Source/FakeItEasy.Specs/DisposableSpecs.cs
Source/FakeItEasy.Specs/FakeItEasy.Specs.csproj
Source/FakeItEasy.Specs/GlobalSuppressions.cs
Source/FakeItEasy.Tests/Core/FakeManagerProviderTests.cs
Source/FakeItEasy/Core/FakeManagerProvider.cs

allow faking of types implementing IDisposable

---

Source/FakeItEasy.Specs/DisposableSpecs.cs
Source/FakeItEasy.Specs/FakeItEasy.Specs.csproj
Source/FakeItEasy.Specs/GlobalSuppressions.cs
Source/FakeItEasy.Tests/Core/FakeManagerProviderTests.cs
Source/FakeItEasy/Core/FakeManagerProvider.cs

Here's how I did it:
```bash
git checkout master
git checkout -b merge-hotifx
git merge hotfix/1.25
git mergetool
git commit -a -m "Merge branch 'hotfix/1.25' into merge-hotfix"
```

Merge hotfix 1.25 to master

---

README.md
Source/FakeItEasy.nuspec

updated README.md and nuspec to 2.x logo

---

README.md

I almost forgot to credit our logo designer :smile:

Add logo credit to readme

---

Source/FakeItEasy-SL/FakeItEasy-SL.csproj
Source/FakeItEasy-SL/SilverlightCompatibility.cs
Source/FakeItEasy.IntegrationTests/ContainerTests.cs
Source/FakeItEasy.IntegrationTests/DummyTests.cs
Source/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs
Source/FakeItEasy.Net35/FakeItEasy.Net35.csproj
Source/FakeItEasy.Specs/DummyFactorySpecs.cs
Source/FakeItEasy.Specs/FakeItEasy.Specs.csproj
Source/FakeItEasy.Specs/LazySpecs.cs
Source/FakeItEasy.Tests/Core/DummyFactoryTests.cs
Source/FakeItEasy.Tests/Core/DynamicContainerTests.cs
Source/FakeItEasy.Tests/Core/EnumerableOfFakeCallsFactory.cs
Source/FakeItEasy.Tests/FakeItEasy.Tests.csproj
Source/FakeItEasy.Tests/LambdaExpressionDummyFactory.cs
Source/FakeItEasy.Tests/TestHelpers/MethodInfoDummyFactory.cs
Source/FakeItEasy.Win8.Tests/Tests.cs
Source/FakeItEasy.Win81.Tests/Tests.cs
Source/FakeItEasy/Core/DynamicContainer.cs
Source/FakeItEasy/Core/FakeScope.cs
Source/FakeItEasy/Core/TypeCatalogue.cs
Source/FakeItEasy/DefaultBootstrapper.cs
Source/FakeItEasy/DummyFactory.cs
Source/FakeItEasy/FakeItEasy.csproj
Source/FakeItEasy/IBootstrapper.cs
Source/FakeItEasy/IDummyFactory.cs
Source/FakeItEasy/ImportsModule.cs

441 rename dummy definition

---

Source/FakeItEasy.nuspec

switch nuspec to square logo

---

Source/FakeItEasy.nuspec

current beta has already been edited
#391

switch nuspec to white padded logo

---

Source/.nuget/packages.config
Source/FakeItEasy.Specs/FakeItEasy.Specs.csproj
Source/FakeItEasy.Specs/packages.config
rakefile.rb

* Updated "Machine.Specifications" package in FakeItEasy.Specs to 0.9.1
* Added "Machine.Specifications.Runner.Console" solution package (the MSpec runners are now in separate packages) and fixed the path in the Rakefile

Upgrade to MSpec 0.9

---

Source/FakeItEasy.Dictionary.xml
Source/FakeItEasy.Specs/PropertySpecs.cs
Source/FakeItEasy/Core/DefaultReturnValueRule.cs
Source/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs

#312 - give unfakeable auto property stable return values

---

Gemfile
Gemfile.lock
how_to_build.md

fixes https://github.com/FakeItEasy/FakeItEasy/issues/242

add Gemfile and Gemfile.lock for bundler

---

Source/FakeItEasy.IntegrationTests/GeneralTests.cs
Source/FakeItEasy/Creation/DefaultFakeCreatorFacade.cs
Source/FakeItEasy/Creation/IFakeOptionsBuilder.cs

Add generic overload of Implements

---

Source/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs
Source/FakeItEasy.Specs/CreationSpecs.cs

making tests language-agnostic

---

Source/FakeItEasy.Tests/Core/ArgumentConstraintTrapTests.cs
Source/FakeItEasy/Core/ArgumentConstraintTrap.cs

making ArgumentConstraintTrap threadsafe

---

Source/FakeItEasy/Core/MethodInfoManager.cs

Fixes layout warning introduced in 470c59feaaa07316c380fcecd43b903c766d72e9.

fixing minor layout issue

---

Source/FakeItEasy.IntegrationTests/GeneralTests.cs

Fixes code analysis warning introduced in e227c9a01c192eae9bcc445a9ee40d3c8b3a6cd4

fixing code analysis warning

---

Source/FakeItEasy.nuspec

expanding title, for SEO

---

.gitignore
Gemfile
Gemfile.lock
how_to_build.md
rakefile.rb

Began by cherry-picking @adamralph's #473.
Will need to adjust build to put artifacts in "artifacts" as well, as was done during part of #442.

make hotfix/1.25 build in new TeamCity environment

---

Source/CommonAssemblyInfo.cs

set version to 1.25.3 for next release

---

Source/FakeItEasy.Specs/CallMatchingSpecs.cs
Source/FakeItEasy.Specs/GlobalSuppressions.cs
Source/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs

Handle OutAttribute (not out) parameters properly

---

Source/FakeItEasy.Net35/ConcurrentDictionary.cs
Source/FakeItEasy.Tests/RaiseTests.cs
Source/FakeItEasy/Core/DelegateRaiser.cs
Source/FakeItEasy/Core/EventHandlerArgumentProviderMap.cs
Source/FakeItEasy/Core/FakeManager.EventRule.cs
Source/FakeItEasy/Core/IEventRaiserArguments.cs
Source/FakeItEasy/Core/MethodInfoManager.cs
Source/FakeItEasy/Core/Raise.of.TEventArgs.cs

As discussed in #499 and #501.
Resolves #499.

Use ConcurrentDictionary instead of Dictionary and locks

---

Source/FakeItEasy.Specs/CallMatchingSpecs.cs
Source/FakeItEasy.Specs/GlobalSuppressions.cs
Source/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs

Here's how I did it:
```bash
git checkout master
git checkout -b merge-hotifx-1.25.3
git merge hotfix/1.25
git commit
```

Merge hotfix 1.25.3

---

Source/packages/repositories.config

re #507
When I reviewed #524 locally in VS, this change was left over in my working dir.

refactor: remove redundant package entries in Source/packages/repositories.config

---

README.md

adding chat to README

---

Source/.nuget/packages.config
Source/FakeItEasy.Specs/AssertingOnSetOnlyPropertiesSpecs.cs
Source/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
Source/FakeItEasy.Specs/AsyncAwaitSpecs.cs
Source/FakeItEasy.Specs/CallMatchingSpecs.cs
Source/FakeItEasy.Specs/CallsBaseMethodsFakeSpecs.cs
Source/FakeItEasy.Specs/ConfigurationSpecs.cs
Source/FakeItEasy.Specs/CreationOptionsSpecs.cs
Source/FakeItEasy.Specs/CreationSpecs.cs
Source/FakeItEasy.Specs/DisposableSpecs.cs
Source/FakeItEasy.Specs/DummyFactorySpecs.cs
Source/FakeItEasy.Specs/EventRaisingSpecs.cs
Source/FakeItEasy.Specs/FakeConfiguratorSpecs.cs
Source/FakeItEasy.Specs/FakeItEasy.Specs.csproj
Source/FakeItEasy.Specs/FakeItEasy.Specs.ruleset
Source/FakeItEasy.Specs/FakeScopeSpecs.cs
Source/FakeItEasy.Specs/FakingDelegates.cs
Source/FakeItEasy.Specs/FakingInternalsSpecs.cs
Source/FakeItEasy.Specs/FixtureInitializationSpecs.cs
Source/FakeItEasy.Specs/LazySpecs.cs
Source/FakeItEasy.Specs/OrderedCallMatchingSpecs.cs
Source/FakeItEasy.Specs/Properties/XunitAssemblyInfo.cs
Source/FakeItEasy.Specs/PropertySpecs.cs
Source/FakeItEasy.Specs/SelfInitializedFakesSpecs.cs
Source/FakeItEasy.Specs/StrictFakeSpecs.cs
Source/FakeItEasy.Specs/UnconfiguredFakeSpecs.cs
Source/FakeItEasy.Specs/packages.config
rakefile.rb

swap mspec for xbehave

---

Source/FakeItEasy.Specs/CreationOptionsSpecs.cs

So @jimmyheaddon doesn't have to when he rebases #462.
@adamralph, how's this sort of thing grab you?
I'm open to, y'know, whatever.

Cleanup creation option specs

---

Source/FakeItEasy.Dictionary.Tests.xml
Source/FakeItEasy.Dictionary.xml
Source/FakeItEasy.IntegrationTests/GeneralTests.cs
Source/FakeItEasy.Tests/Core/DefaultFixtureInitializerTests.cs
Source/FakeItEasy.Tests/Core/TypeCatalogueInstanceProviderTests.cs
Source/FakeItEasy.Tests/NullGuardedConstraint.cs
Source/FakeItEasy.Tests/RepeatedTests.cs
Source/FakeItEasy/A.cs
Source/FakeItEasy/Expressions/CallExpressionParser.cs
Source/FakeItEasy/Expressions/ExpressionCallMatcher.cs

I figured this was a quick fix so went for it, I can't see any breaking changes.

Spelling corrections throughout source

---

CONTRIBUTING.md

Mostly to reference xBehave.net.

updating testing notes for contributors

---

README.md

A couple of badges towards #433.

#433 Add Issue Stats badges to readme.

---

Source/FakeItEasy.Specs/UnconfiguredFakeSpecs.cs
Source/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs

Make properties return dummies

---

Source/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
Source/FakeItEasy.Specs/ConfigurationSpecs.cs

introduced in 8c28a8d1010175ffaeaef5aa305e55fd087f2c25 for #534.

Fix Code Analysis violations

---

Source/.editorconfig
Source/FakeItEasy.sln

Add .editorconfig file

---

Source/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
Source/FakeItEasy.IntegrationTests.VB/packages.config
Source/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
Source/FakeItEasy.IntegrationTests/packages.config
Source/FakeItEasy.Specs/FakeItEasy.Specs.csproj
Source/FakeItEasy.Specs/packages.config
Source/FakeItEasy.Tests/Configuration/ArgumentCollectionTests.cs
Source/FakeItEasy.Tests/FakeItEasy.Tests.csproj
Source/FakeItEasy.Tests/packages.config

and fix test broken by the upgrade.
(as discussed with @blairconrad in https://github.com/FakeItEasy/FakeItEasy/pull/593/files#r51367549)

Upgrade FluentAssertions to 4.2.1

---

Source/FakeItEasy/Creation/IFakeOptions.of.T.cs
Source/FakeItEasy/IArgumentConstraintManager.cs

fixes #580 
fixes #583
replaces #581
replaces #584

Object members

---

Source/FakeItEasy.Net35/FakeItEasy.Net35.csproj
Source/FakeItEasy/Configuration/IArgumentValidationConfiguration.cs
Source/FakeItEasy/Configuration/IAssertConfiguration.cs
Source/FakeItEasy/Configuration/ICallBaseConfiguration.cs
Source/FakeItEasy/Configuration/IExceptionThrowerConfiguration.cs
Source/FakeItEasy/Configuration/IRepeatConfiguration.cs
Source/FakeItEasy/Configuration/IReturnValueConfiguration.cs
Source/FakeItEasy/Configuration/IStartConfiguration.cs
Source/FakeItEasy/Configuration/IVoidConfiguration.cs
Source/FakeItEasy/Configuration/StartConfiguration.cs
Source/FakeItEasy/Creation/IFakeOptions.cs
Source/FakeItEasy/Creation/IFakeOptions.of.T.cs
Source/FakeItEasy/FakeItEasy.csproj
Source/FakeItEasy/IArgumentConstraintManager.cs
Source/FakeItEasy/IHideObjectMembers.cs

585 ihideobjectmembers namespace

---

src/FakeItEasy/Core/ArgumentConstraintTrap.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Tests/Core/ArgumentConstraintTrapTests.cs
tests/FakeItEasy.Tests/Expressions/ExpressionArgumentConstraintFactoryTests.cs

Make A.That throw when used outside of A.CallTo

---

src/FakeItEasy.Net35/Compatibility/ConcurrentQueue.cs
src/FakeItEasy.Net35/FakeItEasy.Net35.csproj
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/FakeScope.cs
tests/FakeItEasy.IntegrationTests/AssertionsTests.cs
tests/FakeItEasy.Net35.Tests/ConcurrentQueueTests.cs
tests/FakeItEasy.Net35.Tests/FakeItEasy.Net35.Tests.csproj
tests/FakeItEasy.Net35.Tests/packages.config

Make FakeAsserter threadsafe

---

src/FakeItEasy.Net35/Compatibility/ConditionalWeakTable.cs
src/FakeItEasy.Net35/Compatibility/EnumerableExtensions.cs
tests/FakeItEasy.Net35.Tests/ConditionalWeakTableTests.cs
tests/FakeItEasy.Net35.Tests/ZipTests.cs

From https://github.com/FakeItEasy/FakeItEasy/pull/620#issuecomment-190708031.

Fix bad shim namespaces

---

FakeItEasy.sln
rakefile.rb

Switch the solution's minimum version to VS2015

---

.mailmap

`git shortlog -sne`
Before:
```
496  Patrik Hägne <patrik@hagne.se>
345  Adam Ralph <adam@adamralph.com>
245  Blair Conrad <blair@blairconrad.com>
118  Blair Conrad <blair.conrad@gmail.com>
25  Thomas Levesque <thomaslevesque@users.noreply.github.com>
```
After:
```
496  Patrik Hägne <patrik@hagne.se>
363  Blair Conrad <blair@blairconrad.com>
345  Adam Ralph <adam@adamralph.com>
25  Thomas Levesque <thomaslevesque@users.noreply.github.com>
```

add entry for Blair Conrad <blair.conrad@gmail.com> to mailmap

---

rakefile.rb

... to be logically consistent for closing issues in the milestone

updated release issue template

---

docs/implicit-creation-options.md

There were several errors in the example code

Fix invalid code in implicit creation options doc

---

src/FakeItEasy/A.cs
src/FakeItEasy/Configuration/UnorderedCallAssertion.cs

connects to #637
Just a couple of tiny things I noticed whilst poking around in the implementation of #637 for my own curiosity.

removed redundant using and partial namespace

---

FakeItEasy.sln

connects to #626
I realised that `mkdocs.yml` was the only top level item missing from the "Solution Items" folder, and then realised that, for consistency, we ought to include the docs in the solution too.

add docs items to solution

---

.mailmap

...plus a commit to sort the entries.

added entry for @thomaslevesque to mailmap

---

tests/FakeItEasy.Tests/ServiceLocatorTests.cs

Add test cases for Should_be_registered_as_non_singleton

---

tests/FakeItEasy.Tests/ServiceLocatorTests.cs

… introduced in #659. Connects to #632.

Fix analysis warning for ServiceLocatorTests

---

tests/FakeItEasy.Tests/ServiceLocatorTests.cs

As discussed in https://github.com/FakeItEasy/FakeItEasy/pull/659/files/95b85957a8b0e987668ebc9868926d229308366b#r59505582
connects to #632

Change iterator properties to array fields

---

README.md

switch links from wiki to readthedocs

---

src/FakeItEasy/Properties/AssemblyInfo.cs

Remove obsolete code analysis suppressions

---

samples/FakeItEasy.Examples.VB/FakeItEasy.Examples.VB.vbproj
samples/FakeItEasy.Examples.VB/packages.config
samples/FakeItEasy.Examples/FakeItEasy.Examples.csproj
samples/FakeItEasy.Examples/packages.config
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.csproj
src/FakeItEasy.Analyzer/packages.config
src/FakeItEasy.Net35/FakeItEasy.Net35.csproj
src/FakeItEasy.Net35/packages.config
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/packages.config
tests/FakeItEasy.Analyzer.Tests/FakeItEasy.Analyzer.Tests.csproj
tests/FakeItEasy.Analyzer.Tests/packages.config
tests/FakeItEasy.IntegrationTests.External/FakeItEasy.IntegrationTests.External.csproj
tests/FakeItEasy.IntegrationTests.External/packages.config
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests.VB/packages.config
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.IntegrationTests/packages.config
tests/FakeItEasy.Net35.Tests/FakeItEasy.Net35.Tests.csproj
tests/FakeItEasy.Net35.Tests/packages.config
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/packages.config
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj
tests/FakeItEasy.Tests/packages.config

Has better support for C# 6, apparently.

refactor: upgrade to StyleCop.MSBuild 4.7.52

---

src/FakeItEasy.Analyzer/DiagnosticDefinitions.cs
src/FakeItEasy.Analyzer/UnusedReturnValueAnalyzer.cs

cosmetic stuff only :lipstick:

minor analyzer refactorings

---

docs/argument-constraints.md
docs/specifying-a-call-to-configure.md
samples/FakeItEasy.Examples.VB/ConfiguringCalls.vb
src/FakeItEasy.Net35/FakeItEasy.Net35.csproj
src/FakeItEasy/A.cs
src/FakeItEasy/Configuration/FakeConfigurationManager.cs
src/FakeItEasy/Configuration/IDoNothingConfiguration.cs
src/FakeItEasy/Configuration/IFakeConfigurationManager.cs
src/FakeItEasy/Configuration/IPropertySetterAnyValueConfiguration.cs
src/FakeItEasy/Configuration/IPropertySetterConfiguration.cs
src/FakeItEasy/Configuration/PropertySetterConfiguration.cs
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.Analyzer.Tests/UnusedCallSpecificationAnalyzerTests.cs
tests/FakeItEasy.Dictionary.Tests.xml
tests/FakeItEasy.IntegrationTests.VB/IndexedPropertyTests.vb
tests/FakeItEasy.Specs/ConfiguringPropertySetterSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/PropertySpecs.cs
tests/FakeItEasy.Specs/UnconfiguredPropertySpecs.cs

New property setter syntax

---

docs/creating-fakes.md

Via @ehajri in [Gitter chat](https://gitter.im/FakeItEasy/FakeItEasy?at=5721d4459b4160fa760a9ca8).

Fix typo in custom attribute builder list building

---

samples/FakeItEasy.Examples.VB/FakeItEasy.Examples.VB.vbproj
samples/FakeItEasy.Examples/FakeItEasy.Examples.csproj
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.IntegrationTests.External/FakeItEasy.IntegrationTests.External.csproj
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Remove ClickOnce bootstrapper from all projects

---

src/FakeItEasy/Core/ICompletedFakeObjectCall.cs
src/FakeItEasy/Core/SequenceNumberManager.cs
src/FakeItEasy/Core/SequentialCallContext.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
tests/FakeItEasy.Tests/FakeCall.cs

Remove SequenceNumber from ICompletedFakeObjectCall

---

src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
tests/FakeItEasy.Tests/Creation/DelegateProxies/DelegateProxyGeneratorTests.cs

- DelegateProxyGenerator
- AssignsOutAndRefParametersSpecs
- DelegateProxyGeneratorTests

minor refactorings of recently touched files

---

src/FakeItEasy/A.cs
src/FakeItEasy/Creation/DefaultFakeCreatorFacade.cs
src/FakeItEasy/Creation/IFakeCreatorFacade.cs
tests/FakeItEasy.IntegrationTests/DummyTests.cs
tests/FakeItEasy.IntegrationTests/GeneralTests.cs

Add CollectionOfDummy. Issue #675.

---

tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt

approve API change from #702
closes #675

update approved API

---

docs/dummies.md

docs: added CollectionOfDummy to dummies.md

---

rakefile.rb

remove JabbR from release notes

---

src/FakeItEasy.Analyzer/UnusedReturnValueAnalyzer.cs

refactor: fix CA violations

---

rakefile.rb

used nuget option -MSBuildVersion to target 14th MSBuild

Fixes #719. fixed build script using MSBuild15 instead of 14

---

src/CommonAssemblyInfo.cs

set version to 2.1.0 for next release

---

rakefile.rb

I noticed a few things that were a little off while working on #665. Figured I might as well get them out of the way first.

Update release instructions

---

.nuget/packages.config
docs/source-stepping.md
mkdocs.yml
rakefile.rb
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.nuspec
src/FakeItEasy/FakeItEasy.nuspec

add source stepping via GitLink

---

src/FakeItEasy.Analyzer/UnusedReturnValueAnalyzer.cs

avoid argument null exception in UnusedReturnValueAnalyzer

---

rakefile.rb

New release targets

---

docs/specifying-return-values.md

Add missing parenthesis

---

tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
tests/FakeItEasy.Specs/StringExtensions.cs

Fixes #582.
I incorporated the `See` extension method we talked about, except where I had to talk about a protected method. Then I fell back to a textual note.

Fix specs after 461

---

docs/creating-fakes.md
docs/dummies.md
src/FakeItEasy/A.cs
src/FakeItEasy/Creation/DefaultFakeCreatorFacade.cs
src/FakeItEasy/Creation/IFakeCreatorFacade.cs
tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt

and for `A.Dummy`, `A.CollectionOfFake` and `A.CollectionOfDummy`
Fixes #482

Add non-generic overloads for A.Fake

---

src/FakeItEasy/A.cs
src/FakeItEasy/Creation/DefaultFakeCreatorFacade.cs
src/FakeItEasy/Creation/IFakeCreatorFacade.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt

Options for fake collection

---

docs/specifying-a-call-to-configure.md

Add documentation example for WithNonVoidReturnType

---

tests/FakeItEasy.Tests/Configuration/AnyCallConfigurationTests.cs

Removes a Code Analysis warning.

Remove word flag, which offended FxCop

---

docs/creating-fakes.md
docs/dummies.md
src/FakeItEasy/A.cs
src/FakeItEasy/Creation/DefaultFakeCreatorFacade.cs
src/FakeItEasy/Creation/IFakeCreatorFacade.cs
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/Sdk/Create.cs
tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/ATests.cs

move non-generic methods from A to Sdk.Create

---

src/CommonAssemblyInfo.cs

set version to 2.2.0 for next release

---

src/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs
src/FakeItEasy/Core/FakeManager.EventRule.cs
src/FakeItEasy/Core/FakeManager.ObjectMemberRule.cs
src/FakeItEasy/Core/FakeManager.PropertySetterRule.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/FakeWrapperConfigurator.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Tests/Core/FakeWrapperConfiguratorTests.cs
tests/FakeItEasy.Tests/Core/WrappedObjectRuleTests.cs

remove write only properties

---

src/FakeItEasy/Configuration/ArgumentCollection.cs
src/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs
src/FakeItEasy/Core/FakeManager.PropertySetterRule.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/TypeCatalogue.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
src/FakeItEasy/Priority.cs
tests/FakeItEasy.Specs/LazySpecs.cs

As discussed in the comments on #790

Simplify to read-only auto-properties

---

src/FakeItEasy.Analyzer/DiagnosticDefinitions.cs

Spotted it while running test coverage

Remove unused method

---

tests/FakeItEasy.Analyzer.Tests/FakeItEasy.Analyzer.Tests.csproj
tests/FakeItEasy.Analyzer.Tests/packages.config
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests.VB/packages.config
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.IntegrationTests/packages.config
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/packages.config
tests/FakeItEasy.Tests.Approval/FakeItEasy.Tests.Approval.csproj
tests/FakeItEasy.Tests.Approval/packages.config
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj
tests/FakeItEasy.Tests/packages.config

Reference xunit.runner.visualstudio from test projects

---

src/CommonAssemblyInfo.cs

setting version to 2.3.0

---

src/FakeItEasy/FakeItEasy.nuspec

remove redundant dependencies element from nuspec

---

.gitignore
FakeItEasy-NetCore.sln
FakeItEasy.sln

address nitpicks from netstd changes

---

.editorconfig
src/FakeItEasy.dotnet/FakeItEasy.dotnet.csproj
src/FakeItEasy.dotnet/FakeItEasy.dotnet.nuget.targets
src/FakeItEasy.dotnet/project.json

Addressing a few more items on [The List](https://github.com/FakeItEasy/FakeItEasy/issues/531#issuecomment-236366247).
connects to #531

add missing bits to FakeItEasy.dotnet.csproj

---

global.json

Addressing an item on [The List](https://github.com/FakeItEasy/FakeItEasy/issues/531#issuecomment-236366247).
connects to #531

Correct name for tests folder

---

src/FakeItEasy.dotnet/FakeItEasy.dotnet.csproj

Connects to #531. Was missed from #617.

Add FakeItEasy.Sdk.Create class to FakeItEasy.dotnet

---

how_to_build.md

New request after my merging fiasco, related to #825

Clarify location of gem install

---

src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Configuration/StartConfiguration.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallRuleTests.cs

Don't return null for value type after DoesNothing

---

src/FakeItEasy/Configuration/StartConfiguration.cs
tests/FakeItEasy.Specs/UnnaturalFakeSpecs.cs

Fix exceptions when configuring unnatural fakes' void methods

---

src/FakeItEasy.netstd/FakeItEasy.netstd.csproj
src/FakeItEasy/Core/FakeManager.EventRule.cs
src/FakeItEasy/Core/WrappedObjectRule.cs
src/FakeItEasy/ExceptionExtensions.cs
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/WrappingFakeSpecs.cs

Wrapping exception

---

tests/FakeItEasy.Specs/WrappingFakeSpecs.cs

Suppress code analysis warning

---

src/FakeItEasy.Analyzer/UnusedReturnValueAnalyzer.cs
tests/FakeItEasy.Analyzer.Tests/UnusedReturnValueAnalyzerTests.cs

Fix analyzer false positive when call spec is returned

---

tests/FakeItEasy.Specs/SelfInitializedFakesSpecs.cs

I thought it might be a good idea to see how our self-initialized fakes actually function.

Add characterization specs for self-initialized fakes

---

src/FakeItEasy.Analyzer/DiagnosticDefinitions.cs
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.csproj
src/FakeItEasy.Analyzer/NonVirtualSetupAnalyzer.cs
src/FakeItEasy.Analyzer/Resources.Designer.cs
src/FakeItEasy.Analyzer/Resources.resx
src/FakeItEasy.Analyzer/SymbolHelpers.cs
src/FakeItEasy.Analyzer/UnusedReturnValueAnalyzer.cs
tests/FakeItEasy.Analyzer.Tests/FakeItEasy.Analyzer.Tests.csproj
tests/FakeItEasy.Analyzer.Tests/NonVirtualSetupAnalyzerTests.cs

Supersedes #826.
@medmondson's work looked good to me, so I thought I'd save him some bookkeeping by creating this PR to
1. Fix two minor Code Analysis warnings that had been introduced
2. rebase on top of master, since there's been a lot of action since the original branch was created,
3. squash all the commits. They were a bit all over the place with the many and incremental comments that the owners had made. For what was ultimately such a small change, with nearly no separable work, I thought one commit would be fine.

Add NonVirtualSetupAnalyzer diagnostic

---

src/FakeItEasy/Configuration/FakeConfigurationManager.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Configuration/StartConfiguration.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Tests/ACallToTests.cs
tests/FakeItEasy.Tests/Configuration/AnyCallConfigurationTests.cs
tests/FakeItEasy.Tests/Configuration/FakeConfigurationManagerTests.cs
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs
tests/FakeItEasy.Tests/Fake.of.T.Tests.cs
tests/FakeItEasy.Tests/TestCases.cs

Fixes #556 
~~This is my first stab at it, still a work in progress.~~
~~The implementation is not yet complete, there are a few other cases that I need to look into.~~
~~The current tests pass, but I need to add new ones to validate the new behavior.~~

Make A.CallTo side-effect free

---

appveyor.yml

Disable publishing of NuGet packages on Pull Requests

---

FakeItEasy.netstd.sln
rakefile.netstd.rb
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.cs
tests/FakeItEasy.Tests.Approval.netstd/FakeItEasy.Tests.Approval.netstd.csproj
tests/FakeItEasy.Tests.Approval.netstd/packages.config
tests/FakeItEasy.Tests.Approval/FakeItEasy.Tests.Approval.csproj

Add approval tests for .NET Standard library

---

src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Tests.ruleset

Implement all interfaces on faked classes

---

README.md

Publish .NET Standard pre-release NuGet feed

---

FakeItEasy.netstd.sln
FakeItEasy.sln
docs/analyzer.md
mkdocs.yml

Add documentation about the analyzer

---

src/FakeItEasy/ExpressionExtensions.cs

Unescape XML entities

---

README.md

Mostly because of hstove/issue_stats#48.

remove issue stats badges

---

src/CommonAssemblyInfo.cs

set version to 2.4.0 for next release

---

src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Tests.ruleset

This reverts commit 207b08915f0bd446c696b3b79dee5bfe0dc06812, reversing
changes made to bef68321dc9e2145ddba079b955a9484c8bc5d29.
Fixes #876

Revert "Merge pull request #863 from thomaslevesque/implement-all-interfaces"

---

src/CommonAssemblyInfo.cs

Set version to 2.3.1

---

src/CommonAssemblyInfo.cs

setting version to 2.4.0

---

Gemfile
Gemfile.lock

Supersedes and closes #881.
We needed the netrc gem to authenticate.

add octokit and netrc to Gemfile

---

CONTRIBUTING.md
README.md
appveyor.yml
rakefile.netstd.rb
rakefile.rb

 make appveyor run *all the things* (so long CodeBetter CI, and thanks for all the fish)

---

README.md

Promote all FakeItEasy packages on NuGet.org

---

appveyor.yml

Appends a random string to the end of PR build numbers:

stop PR's incrementing build number

---

README.md

(and fixed nuget badge format)

added source browser badge

---

src/FakeItEasy.netstd/FakeItEasy.nuspec

Update System.Linq.Expressions to 4.1.0 to match project.json

---

src/CommonAssemblyInfo.cs

preparing for 3.0.0
connects to #902

set version to 3.0.0 for next release

---

src/FakeItEasy/Configuration/IStartConfiguration.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt

Make IStartConfiguration<T> internal

---

src/FakeItEasy/Configuration/AnyCallCallRule.cs
src/FakeItEasy/Configuration/AnyCallConfiguration.cs
src/FakeItEasy/Configuration/PropertySetterConfiguration.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Expressions/ExpressionCallRule.cs

FYI I used this little gem to do most of the heavy lifting https://marketplace.visualstudio.com/items?itemName=DustinCampbell.CEssentials
/ht @DustinCampbell

refactored some members to be expression bodied

---

src/FakeItEasy.netstd/FakeItEasy.netstd.csproj
src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Core/DefaultReturnValueRule.cs
src/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs
src/FakeItEasy/Core/InterceptedFakeObjectCallExtensions.cs
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Specs/LazySpecs.cs
tests/FakeItEasy.Specs/UnconfiguredFakeSpecs.cs
tests/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
tests/FakeItEasy.Tests/Core/DefaultFixtureInitializerTests.cs
tests/FakeItEasy.Tests/Core/DefaultSutInitializerTests.cs

all default returns are dummies (or as close as we can come)

---

src/FakeItEasy.netstd/FakeItEasy.netstd.csproj
src/FakeItEasy/Configuration/AnyCallConfiguration.cs
src/FakeItEasy/Configuration/IAfterCallConfiguredConfiguration.cs
src/FakeItEasy/Configuration/IAfterCallConfiguredWithOutAndRefParametersConfiguration.cs
src/FakeItEasy/Configuration/ICallBaseConfiguration.cs
src/FakeItEasy/Configuration/IDoNothingConfiguration.cs
src/FakeItEasy/Configuration/IExceptionThrowerConfiguration.cs
src/FakeItEasy/Configuration/IOutAndRefParametersConfiguration.cs
src/FakeItEasy/Configuration/IReturnValueConfiguration.cs
src/FakeItEasy/Configuration/PropertySetterConfiguration.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/ExceptionThrowerConfigurationExtensions.cs
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/OutAndRefParametersConfigurationExtensions.cs
src/FakeItEasy/ReturnValueConfigurationExtensions.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/Configuration/AnyCallConfigurationTests.cs
tests/FakeItEasy.Tests/OutAndRefParametersConfigurationExtensionsTests.cs
tests/FakeItEasy.Tests/ReturnValueConfigurationExtensionsTests.cs

Rename IAfterCallSpecifiedConfiguration to IAfterCallConfiguredConfiguration

---

rakefile.rb

default version suffix while Castle.Core is pre-release

---

src/FakeItEasy.netstd/project.json
src/FakeItEasy.nuspec
tests/FakeItEasy.IntegrationTests.netstd/project.json
tests/FakeItEasy.Tests.netstd/project.json
tests/FakeItEasy.Tests/FakeOptionsBuilderTests.cs

Inspired by a discussion in #928.
Am I crazy?

Clean up project.jsons

---

FakeItEasy.sln
rakefile.rb
tests/FakeItEasy.Specs.netstd/FakeItEasy.Specs.netstd.xproj
tests/FakeItEasy.Specs.netstd/project.json
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/DummyFactorySpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
tests/FakeItEasy.Specs/FakingInternalsSpecs.cs

Connects to #531 
Well, it wasn't as painful as I feared it would be :wink:

Add a .NET Core test project for FakeItEasy.Specs

---

src/FakeItEasy/Configuration/IDoNothingConfiguration.cs
src/FakeItEasy/Configuration/IOutAndRefParametersConfiguration.cs
src/FakeItEasy/Configuration/IRepeatSpecification.cs
src/FakeItEasy/Configuration/IWhereConfiguration.cs
src/FakeItEasy/IOutputWriter.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt

Hide object members on Fluent API interfaces

---

src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
src/FakeItEasy/Expressions/ParsedArgumentExpression.cs
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests.VB/RefArgumentConstraintTests.vb

Fix bug for constraint on ref or out argument

---

src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
src/FakeItEasy/Expressions/ParsedArgumentExpression.cs
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests.VB/RefArgumentConstraintTests.vb

Connects to #899
(I just cherry-picked the merge commit)

Backport fix for #899 to 2.x

---

src/FakeItEasy/Configuration/PropertySetterConfiguration.cs
tests/FakeItEasy.Specs/ConfiguringPropertySetterSpecs.cs

Fix stack overflow in CallToSet configuration

---

src/FakeItEasy/Core/DefaultExceptionThrower.cs
src/FakeItEasy/Creation/IFakeAndDummyManager.cs
src/FakeItEasy/ExceptionMessages.Designer.cs
src/FakeItEasy/ExceptionMessages.resx
tests/FakeItEasy.IntegrationTests/GeneralTests.cs
tests/FakeItEasy.Tests/Core/DefaultExceptionThrowerTests.cs

Removed the last references to IFakeObjectContainer

---

src/CommonAssemblyInfo.cs

preparing for 3.1.0
Connects to #986

set version to 3.1.0 for next release

---

tests/FakeItEasy.Analyzer.CSharp.Tests/UnusedReturnValueAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/UnusedReturnValueAnalyzerTests.cs

Add the four missing tests for #765 
fixes #765

Added missing tests

---

src/FakeItEasy/Core/DefaultArgumentConstraintManager.cs
src/FakeItEasy/TypeExtensions.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Fix NRE when matching null arg with value-type constraint

---

src/FakeItEasy/TypeExtensions.cs
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj
tests/FakeItEasy.Tests/TypeExtensionsTests.cs

Don't consider open generic types to be instantiable

---

rakefile.rb

Instruct releaser to use Deploy to push nupkgs

---

src/FakeItEasy/Core/DefaultFakeManagerAccessor.cs
src/FakeItEasy/Core/IFakeManagerAccessor.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/Fake.cs
src/FakeItEasy/FakeFacade.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Ensure that calls can be described when ToString() throws

---

CONTRIBUTING.md

Improved readability of CONTRIBUTING.md by
- adding links for further information where appropriate
- improved formatting
- added a table in the last chapter "Sending a Pull Request" to make it more readable
PR originally inspired by #1000 and some Gitter chat.

Improved readability of CONTRIBUTING.md

---

src/FakeItEasy/Core/DefaultArgumentConstraintManager.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/UnusedReturnValueAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/UnusedReturnValueAnalyzerTests.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/EventRaisingSpecs.cs

I didn't track down when they were all introduced, because I'm a little lazy.

Fix various code analysis warnings

---

src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Fake.cs
src/FakeItEasy/FakeFacade.cs
tests/FakeItEasy.Specs/FakeSpecs.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/FakeFacadeTests.cs

Provide FakeManager.ClearRecordedCalls

---

src/CommonAssemblyInfo.cs

Set version to 3.2.0

---

docs/argument-constraints.md
src/FakeItEasy/ArgumentValidationConfigurationExtensions.cs
src/FakeItEasy/Configuration/ArgumentCollection.cs
tests/FakeItEasy.Specs/ArgumentMatchingSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/Configuration/ArgumentCollectionTests.cs
tests/FakeItEasy.Tests/Core/FakeCallEqualityComparerTests.cs
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj
tests/FakeItEasy.Tests/FakeObjectCallExtensionsTests.cs
tests/FakeItEasy.Tests/TestHelpers/FakeMethodHelper.cs

Strongly typed WhenArgumentsMatch

---

src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/FakeOptionsExtensions.cs
tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/StrictFakeSpecs.cs
tests/FakeItEasy.Tests/FakeOptionsExtensionsTests.cs

Fully describe call to non-configured method on strict Fake

---

tests/FakeItEasy.Specs/CancellationSpecs.cs
tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
tests/FakeItEasy.Specs/ThenSpecs.cs
tests/FakeItEasy.Specs/ThrowsAsyncSpecs.cs
tests/FakeItEasy.Specs/WrappingFakeSpecs.cs
tests/FakeItEasy.Tests.ruleset

Make spec classes static

---

README.md

add coverity badge

---

src/FakeItEasy/Fake.of.T.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt

Stop implementing IStartConfiguration<T> in Fake<T>

---

src/CommonAssemblyInfo.cs

Set version to 3.3.0

---

src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
tests/FakeItEasy.IntegrationTests/Assertions/ExceptionMessagesTests.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/OrderedCallMatchingSpecs.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallMatcherTests.cs

Include parameter name in call description

---

src/FakeItEasy/A.cs
src/FakeItEasy/Core/InterceptedFakeObjectCallExtensions.cs
src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
src/FakeItEasy/Creation/DummyValueCreationSession.cs
src/FakeItEasy/Fake.of.T.cs
src/FakeItEasy/RootModule.cs
src/FakeItEasy/Sdk/Create.cs
tests/FakeItEasy.IntegrationTests/DummyTests.cs
tests/FakeItEasy.Tests/ServiceLocatorTests.cs

Fixes #769.
I also have some ideas about continuing the work a little with some other classes. There's more duplication to be removed, I think.

Make IFakeAndDummyManager a singleton 

---

src/FakeItEasy/Configuration/DefaultInterceptionAsserter.cs
src/FakeItEasy/Core/DefaultFakeObjectCallFormatter.cs
src/FakeItEasy/MethodBaseExtensions.cs
tests/FakeItEasy.IntegrationTests/ExceptionMessagesTests.cs
tests/FakeItEasy.Tests/Configuration/DefaultInterceptionAsserterTests.cs

Include name of the method that can't be intercepted in the error message

---

src/FakeItEasy/Core/DefaultFakeObjectCallFormatter.cs
src/FakeItEasy/Creation/ProxyOptions.cs
src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/FakeOptionsBuilder.cs
src/FakeItEasy/MethodBaseExtensions.cs
src/FakeItEasy/TypeExtensions.cs
tests/FakeItEasy.IntegrationTests/ExceptionMessagesTests.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Use CLR formatting for types and methods rather than C# formatting

---

src/FakeItEasy.netstd/FakeItEasy.netstd.csproj
src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
src/FakeItEasy/Creation/DummyCreationSession.cs
src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
src/FakeItEasy/Creation/IDummyValueResolver.cs
src/FakeItEasy/Creation/IFakeObjectCreator.cs
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Tests/Creation/DefaultFakeObjectCreatorTests.cs
tests/FakeItEasy.Tests/Creation/DummyValueResolverTests.cs
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Reduce temporary objects created when making Dummies

---

docs/argument-constraints.md
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
tests/FakeItEasy.Tests.Approval.netstd/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi.approved.txt
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/IsNotNullTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/NullableIsNotNullTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/NullableIsNullTests.cs
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Fixes #1062 
Also includes `IsNull` and `IsNotNull` overloads for nullable value types

IsNotNull constraint

---

docs/analyzer.md

Fixes #1005. Closes #1067.
(Well, most of the work was done in #1065. This is just the finishing touch.)

Add documentation for FakeItEasy0003 diagnostic

---

src/FakeItEasy.Analyzer.Shared/NonVirtualSetupAnalyzer.cs
src/FakeItEasy.Analyzer.Shared/UnusedReturnValueAnalyzer.cs

Simplify UnusedReturnValueAnalyzer and NonVirtualSetupAnalyzer

---

tests/FakeItEasy.Specs/CreationSpecs.cs

Avoid concurrent access to shared FakedClass.ParameterListLengthsForAttemptedConstructors

---

src/FakeItEasy/ArgumentConstraintManagerExtensions.cs

Suppress CA1006 analyzer warning

---

src/FakeItEasy.Analyzer.Shared/NonVirtualSetupAnalyzer.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/NonVirtualSetupAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/NonOverridableSetupAnalyzerTests.cs

Fix false call setup warning when property index is a non-virtual member

---

CONTRIBUTING.md
README.md

Replace master with develop as default branch

---

src/FakeItEasy.Analyzer.Shared/DiagnosticDefinitions.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/ArgumentConstraintOutsideCallSpecAnalyzerTests.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/NonVirtualSetupAnalyzerTests.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/UnusedReturnValueAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/ArgumentConstraintOutsideCallSpecAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/NonOverridableSetupAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/UnusedReturnValueAnalyzerTests.cs

Fix wrong diagnostic id for FakeItEasy0003

---

build.csx
tests/FakeItEasy.Analyzer.CSharp.Tests/FakeItEasy.Analyzer.CSharp.Tests.csproj
tests/FakeItEasy.Analyzer.VisualBasic.Tests/FakeItEasy.Analyzer.VisualBasic.Tests.csproj
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests.VB/packages.config
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests.Approval/FakeItEasy.Tests.Approval.csproj
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Fixes #1100
The second commit changes the order of build targets. Whether we keep it or not is open to discussion.

Fix PdbGit

---

src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Configuration/UnorderedCallAssertion.cs
src/FakeItEasy/Core/FakeAsserter.cs
src/FakeItEasy/Core/IFakeAsserter.cs
src/FakeItEasy/Core/SequentialCallContext.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs
tests/FakeItEasy.Tests/Core/FakeAsserterTests.cs

Make MustHaveHappened build call description lazily

---

tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj

Supports #1008.
Forgotten from a692fc861aa3f558ed87e77753daff3145420256 (#1108).

Enable specs for EventArg-less raising

---

src/FakeItEasy.Analyzer/CSharp/Resources.resx
src/FakeItEasy.Analyzer/VisualBasic/Resources.resx
src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidator.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/NonVirtualSetupAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/NonOverridableSetupAnalyzerTests.cs
tests/FakeItEasy.IntegrationTests/ExceptionMessagesTests.cs
tests/FakeItEasy.IntegrationTests/GeneralTests.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Tests/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidatorTests.cs

Improve non-virtual member configuration message

---

src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidator.cs
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.Specs/FakingInternalsSpecs.cs

Better error message when faking inaccessible methods

---

.gitignore
FakeItEasy.sln
GitVersion.yml
build.csx
packages.config
src/CommonAssemblyInfo.cs
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.VisualBasic.csproj
src/FakeItEasy/FakeItEasy.csproj

Use GitVersion to generate version numbers

---

src/FakeItEasy.nuspec

Reference Castle.Core 4.1.0

---

src/FakeItEasy.nuspec

Hotfix 3.4.1

---

src/FakeItEasy/A.of.T.cs
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/Core/DefaultArgumentConstraintManager.cs
src/FakeItEasy/IArgumentConstraintManager.cs
src/FakeItEasy/IArgumentConstraintManagerFactory.cs
src/FakeItEasy/INegatableArgumentConstraintManager.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/CancellationTokenIsCanceledTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/CancellationTokenIsNotCanceledTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/CollectionContainsTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/CollectionIsEmptyTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/ComparableGreaterThanTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/DerivedTypeArgumentTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/EqualToConstraintTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/IsInstanceOfTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/IsNotNullTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/IsNullTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/IsSameSequenceAsTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/NullCheckedMatchesConstraint.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/NullableIsNotNullTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/NullableIsNullTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/SameAsConstraintTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringContainsTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringEndsWithTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringIsNullOrEmptyTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringStartsWithTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintTestBase.of.T.cs

Don't expose Not after Not in argument constraint

---

src/FakeItEasy/FakeOptionsExtensions.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt

Noticed when I was reading about #463.

Rename some optionsBuilders to options

---

src/FakeItEasy/Core/CompletedFakeObjectCall.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
src/FakeItEasy/SelfInitializedFakes/SelfInitializationRule.cs
tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
tests/FakeItEasy.Tests/SelfInitializedFakes/SelfInitializationRuleTests.cs

Fix: assigning ref param overwrites recorded argument

---

src/FakeItEasy/Core/CompletedFakeObjectCall.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
src/FakeItEasy/SelfInitializedFakes/SelfInitializationRule.cs
tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
tests/FakeItEasy.Tests/SelfInitializedFakes/SelfInitializationRuleTests.cs

Hotfix 3.4.2

---

src/FakeItEasy/Core/CompletedFakeObjectCall.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs

Merge hotfix 3.4.2 into develop

---

appveyor.yml

Fixes #1039.
I expect. I'm not really sure how to test this without actually merging and then tagging something.
Wanna give it a go and release a 4.0.0 alpha? :wink:

Deploy to NuGet on new tag

---

docs/raising-events.md
src/FakeItEasy/Core/DelegateRaiser.cs
src/FakeItEasy/Core/DynamicRaiser.cs
src/FakeItEasy/Raise.cs
src/FakeItEasy/ValueProducerSignatureHelper.cs
tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt

Raise for free-form events

---

build.csx
src/FakeItEasy.Analyzer.nuspec
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.VisualBasic.csproj
src/FakeItEasy.Analyzer/packages.analyzer.targets
src/FakeItEasy/FakeItEasy.csproj
src/packages.targets

Split C# and VB analyzers into separate packages, use dotnet pack to build packages

---

docs/raising-events.md
src/FakeItEasy/Raise.cs
tests/FakeItEasy.IntegrationTests.VB/RaisingEventsTests.vb
tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt

Deprecate Raise.With<TEventHandler>

---

src/FakeItEasy/Core/CompletedFakeObjectCall.cs
src/FakeItEasy/Core/ICompletedFakeObjectCall.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests/FakeCall.cs

Add updated parameters

---

docs/analyzer.md
src/FakeItEasy.Analyzer/ArgumentConstraintAnalyzerBase.cs
src/FakeItEasy.Analyzer/ArgumentConstraintNullabilityMismatchAnalyzer.cs
src/FakeItEasy.Analyzer/ArgumentConstraintNullabilityMismatchCodeFixProvider.cs
src/FakeItEasy.Analyzer/ArgumentConstraintOutsideCallSpecAnalyzer.cs
src/FakeItEasy.Analyzer/CSharp/Resources.resx
src/FakeItEasy.Analyzer/DiagnosticDefinitions.cs
src/FakeItEasy.Analyzer/SymbolExtensions.cs
src/FakeItEasy.Analyzer/SymbolHelpers.cs
src/FakeItEasy.Analyzer/VisualBasic/Resources.resx
tests/FakeItEasy.Analyzer.CSharp.Tests/ArgumentConstraintNullabilityMismatchAnalyzerTests.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/CodeFixVerifier.Helper.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/CodeFixVerifier.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/ArgumentConstraintNullabilityMismatchAnalyzerTests.cs

Fixes #1060 
WIP because only the analyzer is done; I also intend to add a code fix.

Nullable constraint analyzer

---

src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.VisualBasic.csproj
tests/FakeItEasy.Analyzer.CSharp.Tests/FakeItEasy.Analyzer.CSharp.Tests.csproj
tests/FakeItEasy.Analyzer.VisualBasic.Tests/FakeItEasy.Analyzer.VisualBasic.Tests.csproj

Fix analyzer dependencies

---

appveyor.yml

Invoke build under cmd, not PowerShell

---

src/FakeItEasy.Analyzer.nuspec

Update Analyzer description to point to language-specific nupkgs

---

docs/argument-constraints.md
src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Don't allow nested argument constraints

---

deploy.ps1

Include nuget path when pushing

---

appveyor.yml
deploy.ps1

Use new nuget API key and better server URL

---

deploy.ps1

Fixes #1183.
- Stops at first PowerShell error
- Stops if nuget windows executable returns non-zero
- Stops if no artifacts are found
- Prints a message at end of deployment so it's easier to tell if we
stopped early

Stop deployment at first error

---

appveyor.yml

Fix failed build detection in AppVeyor

---

build.csx
samples/FakeItEasy.Examples.VB/FakeItEasy.Examples.VB.vbproj
tests/FakeItEasy.IntegrationTests.VB/FakeItEasy.IntegrationTests.VB.vbproj
tests/FakeItEasy.IntegrationTests.VB/packages.config

Fixes #1185 
Seems to work fine with VS2017 15.3 installed. Not sure why it works, though, since we're still using .NET Core SDK 1.0.4...

[WIP] Migrate VB projects to SDK-style projects

---

how_to_build.md

Supports #1185.
I thought of this just after merging #1187.

Update required tool version to 15.3

---

src/FakeItEasy.Analyzer/ArgumentConstraintOutsideCallSpecAnalyzer.cs
src/FakeItEasy.Analyzer/SymbolHelpers.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/ArgumentConstraintOutsideCallSpecAnalyzerTests.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/UnusedReturnValueAnalyzerTests.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/CodeFixVerifier.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/DiagnosticVerifier.Helper.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/DiagnosticVerifier.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/ArgumentConstraintOutsideCallSpecAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/UnusedReturnValueAnalyzerTests.cs

Fix FakeItEasy0003 false positive

---

GitVersion.yml

Pin assembly version to Major.0.0.0

---

build.csx

Use MSBuild binary log

---

docs/formatting-argument-values.md
src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/Core/FakeAsserter.cs
src/FakeItEasy/Core/SequentialCallContext.cs
src/FakeItEasy/Core/TypeCatalogue.cs
src/FakeItEasy/DefaultOutputWriter.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/FakeObjectCallExtensions.cs
src/FakeItEasy/RootModule.cs
src/FakeItEasy/StringBuilderOutputWriter.cs
src/FakeItEasy/ValueProducerSignatureHelper.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Tests/ActionOverWriterValueFormatter.cs
tests/FakeItEasy.Tests/ArgumentConstraintTestBase.cs
tests/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
tests/FakeItEasy.Tests/Core/ArgumentValueFormatterTests.cs
tests/FakeItEasy.Tests/Core/CallWriterTests.cs
tests/FakeItEasy.Tests/Core/DefaultArgumentConstraintManagerTests.cs
tests/FakeItEasy.Tests/Core/FakeAsserterTests.cs
tests/FakeItEasy.Tests/CustomArgumentConstraints.cs
tests/FakeItEasy.Tests/Expressions/ArgumentConstraints/AggregateArgumentConstraintTests.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallMatcherTests.cs
tests/FakeItEasy.Tests/FakeObjectCallExtensionsTests.cs
tests/FakeItEasy.Tests/GenericATests.cs
tests/FakeItEasy.Tests/NullGuardedAssertion.cs

Make value formatting more consistent

---

src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.Specs/FakingInternalsSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt

Upgrade to Castle.Core 4.2.0

---

src/FakeItEasy.Analyzer/DiagnosticDefinitions.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/NonVirtualSetupAnalyzerTests.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/NonOverridableSetupAnalyzerTests.cs

Change FakeItEasy0002 diagnostic to an error (was a warning)

---

build.csx

Build projects in parallel

---

docs/argument-constraints.md
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/IsSameSequenceAsTests.cs

Add params overload to IsSameSequenceAs

---

.gitignore
packages.config
prepare_release.cmd
prepare_release.csx

Add script to automate release branch creation, PR

---

src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Fix false positive "nested argument constraint" when constraint is of the wrong type

---

prepare_release.csx

Explicitly add build, documentation labels to new release issue

---

src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Fix missed nested constraint

---

src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Handle multiple converts

---

prepare_release.csx

Remove unnecessary reference from prepare_release.csx

---

global.json
how_to_build.md

Upgrade to .NET Core SDK 2.0.2

---

FakeItEasy.sln

Contributes to #1249.
I should've thought of this when reviewing #1250.

Align Solution items with uncluttered up root directory

---

docs/argument-constraints.md
docs/assigning-out-and-ref-parameters.md

Document ref argument matching

---

docs/assertion.md
docs/assigning-out-and-ref-parameters.md
docs/doing-nothing.md
docs/formatting-argument-values.md
docs/specifying-a-call-to-configure.md
docs/specifying-return-values.md

Or, as I wanted to call it, "adopt bad behavior".

Change "behaviour" to "behavior" throughout docs

---

src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.Specs/CreationSpecs.cs

Updated Castle.Core from 4.2.0 to 4.2.1 to fix issue described in #1257.

---

tools/deploy.ps1

Fix deployment to NuGet.org

---

src/Directory.Build.props
src/FakeItEasy.Analyzer/Directory.Build.targets
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.VisualBasic.csproj
src/FakeItEasy/FakeItEasy.csproj

Fix generation of analyzer packages

---

src/FakeItEasy.Analyzer/Directory.Build.props
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj
src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.VisualBasic.csproj

Refactor IncludeBuildOutput property in Directory.Build.props

---

docs/raising-events.md

Document Raise.FreeForm.With limitation and dependency

---

docs/raising-events.md
src/FakeItEasy/Raise.cs
tests/FakeItEasy.IntegrationTests.VB/RaisingEventsTests.vb
tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd.approved.txt

Add Raise.FreeForm<TEventHandler> for Visual Basic

---

src/FakeItEasy/Core/CallWriter.cs
src/FakeItEasy/Core/SequentialCallContext.cs
tests/FakeItEasy.IntegrationTests/Assertions/ExceptionMessagesTests.cs
tests/FakeItEasy.Specs/OrderedCallMatchingSpecs.cs
tests/FakeItEasy.Tests/Core/CallWriterTests.cs

Remove 'repeated' from completed call assertion messages

---

src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
tests/FakeItEasy.Specs/CallDescriptionsInAssertionSpecs.cs

Fixes #1298 
I didn't find a good place to put those assertions, so I created a new class.

Fix setter description in assertion

---

src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
tests/FakeItEasy.Specs/CallDescriptionsInAssertionSpecs.cs

Fixes #1299
Note: Don't merge yet. This PR is built on top of #1301, so it includes the commits from that branch. I'll rebase it on develop after #1301 is merged.

Make description of asserted call consistent with actual calls for property accessors

---

docs/creating-fakes.md
docs/specifying-a-call-to-configure.md
docs/what-can-be-faked.md

Document fake delegates

---

FakeItEasy.sln

Remove .nuget Solution Items

---

tools/build.csx

Turn off test auto-reporting

---

src/FakeItEasy.Analyzer/RepeatedAssertionAnalyzer.cs
tests/FakeItEasy.Analyzer.CSharp.Tests/RepeatedAssertionAnalyzerTests.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/DiagnosticVerifier.Helper.cs

Fix NullReferenceException in RepeatedAssertionAnalyzer

---

README.md
appveyor.yml
tools/build.csx

Remove coverity build

---

src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
tests/FakeItEasy.IntegrationTests/Assertions/ExceptionMessagesTests.cs
tests/FakeItEasy.Specs/CallDescriptionsInAssertionSpecs.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/StringExtensions.cs
tests/FakeItEasy.Tests/Expressions/ArgumentConstraints/EqualityArgumentConstraintTests.cs

Use ArgumentValueFormatter in EqualityArgumentConstraint

---

src/FakeItEasy/Creation/FakeObjectCreator.cs
tests/FakeItEasy.Specs/CreationSpecs.cs

Resolve constructor arguments lazily

---

README.md

we've been out of pre-release for 15 months!

Update supported platforms in README

---

tests/FakeItEasy.Specs/CreationSpecs.cs

Quiets warning introduced in #1360 (part of #1355).

Seal ArgumentThatShouldNeverBeResolved

---

src/FakeItEasy/Core/StrictFakeRule.cs
src/FakeItEasy/FakeOptionsExtensions.cs

Use custom rule for strict fakes

---

src/FakeItEasy/Configuration/AnyCallConfiguration.cs

Add missing null checks in AnyCallConfiguration

---

src/FakeItEasy/Core/DefaultExceptionThrower.cs
src/FakeItEasy/Core/IExceptionThrower.cs
src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
src/FakeItEasy/Creation/ResolvedConstructor.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Tests/Core/DefaultExceptionThrowerTests.cs
tests/FakeItEasy.Tests/Creation/DefaultFakeObjectCreatorTests.cs

Cache Fake and Dummy constructors

---

tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs

Remove unnecessary pragma about obsolete code

---

tools/build.csx

add missing static method qualification

---

tests/FakeItEasy.Specs/UserCallbackExceptionSpecs.cs

Introduced in adf8d8e73c51866f87a083b9d5fdf74ca1f3d8a6

Quell CA1040:AvoidEmptyInterfaces warning

---

src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
src/FakeItEasy/FakeItEasy.csproj
src/FakeItEasy/ParameterInfoExtensions.cs
tests/FakeItEasy.Specs/InParametersSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt

Fixes #1388.
Fixes #1390.
Fixes #1391.

Reject attempts to assign values to in parameters

---

src/FakeItEasy/Creation/CreationResult.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
tests/FakeItEasy.IntegrationTests/GeneralTests.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs

Stop trying parameterless constructor

---

docs/specifying-a-call-to-configure.md

Include action in CallTo documentation

---

docs/creating-fakes.md

Remove reference to call recording/playback functionality

---

tools/FakeItEasy.Build/Program.cs

switch targets to using enumerable inputs

---

tools/FakeItEasy.Build/Program.cs

See https://github.com/FakeItEasy/FakeItEasy/pull/1422#issuecomment-417941702

remove the "clean" build target

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj

- [Attempt to automatically enable console colors in Windows](https://github.com/adamralph/bullseye/issues/73)
- [Source stepping](https://github.com/adamralph/bullseye/issues/52)

upgrade to Bullseye 1.2.0

---

tools/FakeItEasy.PrepareRelease/Program.cs

Fix prepare release

---

tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Tests/FakeItEasy.Tests.csproj

Test under netcoreapp2.1

---

src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/Creation/StringDummyFactory.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs

Optimize dummy creation

---

tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.IntegrationTests/StringArgumentConstraints.cs

Introduced when `netcoreapp2.1` targets were added to tests.

Fix CA1307 warning

---

tools/Directory.Build.props

https://github.com/adamralph/simple-exec/issues/48

update to SimpleExec 3.0.0

---

appveyor.yml

Set NuGet server URL

---

src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Core/FakeAsserter.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Tests/ConcurrentCallTests.cs
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs
tests/FakeItEasy.Tests/Core/FakeAsserterTests.cs

Fix race condition when recording concurrent calls

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj

@blairconrad RC3 contains https://github.com/adamralph/bullseye/issues/112

upgrade to Bullseye 2.0.0 RC3

---

src/FakeItEasy/Compatibility/ReflectionExtensions.cs
src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs

Cache FakeOption constructor

---

src/FakeItEasy/Core/AssemblyExtensions.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidator.cs

Use ProxyUtils to determine if a type is a proxy

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj

switch to Bullseye 2.1.0 RTM

---

docs/advanced-usage.md
docs/assertion.md
mkdocs.yml

Document advanced usage methods

---

src/FakeItEasy/Core/IInterceptedFakeObjectCall.cs
src/FakeItEasy/Core/InterceptedFakeObjectCall.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd16.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd20.approved.txt
tests/FakeItEasy.Tests/TestHelpers/ExpressionHelper.cs

Fixes #1505
Pretty simple thanks to your previous work on this, @blairconrad!

Remove IInterceptedFakeObjectCall.AsReadOnly

---

FakeItEasy.sln
docs/advanced-usage.md
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/IInterceptionListener.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd16.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd20.approved.txt
tests/FakeItEasy.Tests/Core/FakeManagerTests.cs
tests/FakeItEasy.Tests/Expressions/ExpressionArgumentConstraintFactoryTests.cs

Stop passing rule to interception listener

---

src/FakeItEasy/Core/FakeManager.cs

Stop recording rule used

---

tools/FakeItEasy.Build/Program.cs

I spotted a few things which were redundant and/or could be simplified.

refactor build script

---

src/FakeItEasy/A.cs
src/FakeItEasy/Core/DelegateRaiser.cs
src/FakeItEasy/Fake.of.T.cs
src/FakeItEasy/Raise.cs
tests/FakeItEasy.IntegrationTests/GeneralTests.cs
tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd16.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd20.approved.txt
tests/FakeItEasy.Tests/Core/FakeManagerTests.cs
tests/FakeItEasy.Tests/TestHelpers/ExpressionHelper.cs

Limit typeparams in Generic Fake creation methods to reference types

---

src/FakeItEasy/BehaviorLifetimeConfigurationExtensions.cs
src/FakeItEasy/Configuration/IAfterCallConfiguredConfiguration.cs
src/FakeItEasy/Configuration/IBehaviorLifetimeConfiguration.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd16.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd20.approved.txt
tests/FakeItEasy.Tests/BehaviorLifetimeConfigurationExtensionsTests.cs

Rename IRepeatConfiguration to IBehaviorLifetimeConfiguration

---

src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
tests/FakeItEasy.Specs/CreationSpecs.cs

Stop faking delegates not accessible to DynamicProxy

---

CONTRIBUTING.md
README.md
tools/FakeItEasy.PrepareRelease/Program.cs

Switch from Git Flow to GitHub flow

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj

To get the fix for https://github.com/adamralph/bullseye/issues/180.

update Bullseye to 2.3.0.beta.4

---

src/Directory.Build.props

Remove MinVerMajorMinor

---

tools/FakeItEasy.PrepareRelease/Program.cs

Update release attributes when renaming

---

src/FakeItEasy/Configuration/BuildableCallRule.cs
tests/FakeItEasy.Specs/UserCallbackExceptionSpecs.cs

Dont wrap exception in invokes

---

src/FakeItEasy/ExpressionExtensions.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs

Create properly-typed arrays

---

src/Directory.Build.props

Embed SPDX license identifier in the package

---

.gitignore

Inspired by https://github.com/FakeItEasy/FakeItEasy/pull/1516

Remove defunct .gitignore entries

---

src/FakeItEasy/Core/FakeManager.EventRule.cs
tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Tests/TestHelpers/ClassWithInternalEventVisibleToDynamicProxy.cs

Raise internal events

---

tests/FakeItEasy.Tests/TestHelpers/ClassWithInternalEventVisibleToDynamicProxy.cs

Suppress CS0067 warning for unused event

---

docs/creating-fakes.md
src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/Core/FakeManager.ObjectMemberRule.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/FakeManagerProvider.cs
src/FakeItEasy/Creation/FakeOptions.cs
src/FakeItEasy/Creation/IFakeOptions.cs
src/FakeItEasy/Creation/IFakeOptions.of.T.cs
src/FakeItEasy/Creation/IProxyOptions.cs
src/FakeItEasy/Creation/ProxyOptions.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd16.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd20.approved.txt
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs
tests/FakeItEasy.Tests/Core/FakeManagerProviderTests.cs
tests/FakeItEasy.Tests/Core/FakeManagerTests.cs

Add support for named fakes

---

how_to_build.md
src/FakeItEasy/FakeItEasy.csproj

Upgrade ILMerge to 3.0.21

---

src/FakeItEasy/Core/FakeManager.AutoFakePropertyRule.cs
src/FakeItEasy/Core/FakeManager.PropertySetterRule.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/ReturnValueConfigurationExtensions.cs
tests/FakeItEasy.IntegrationTests/ConcurrentCallTests.cs
tests/FakeItEasy.Specs/FakeManagerSpecs.cs
tests/FakeItEasy.Tests/Core/FakeManagerTests.cs

Make concurrent calls to Fakes threadsafe

---

src/FakeItEasy/ReturnValueConfigurationExtensions.cs
tests/FakeItEasy.Tests/ReturnValueConfigurationExtensionsTests.cs

Null-guard ReturnsNextFromSequence

---

tools/Directory.Build.props

Upgrade SimpleExec to 5.0.1

---

src/FakeItEasy/Core/FakeManager.cs

Record call before applying the best matching rule

---

tests/FakeItEasy.Specs/OrderedCallMatchingSpecs.cs

Tests that #1583 stays fixed.
I forgot this before.

Test that calls are recorded before applying best matching rule

---

README.md
docs/index.md
docs/why-was-fakeiteasy-created.md
src/FakeItEasy/FakeItEasy.csproj

Fixes #1587.
Also replaced one mention of framework in the .csproj description.

Replace the term framework with library

---

tools/FakeItEasy.Build/FakeItEasy.Build.csproj

Contains a minor fix: adamralph/bullseye#254

update Bullseye from 2.4.0-beta.1 to 2.4.0-rc.2

---

src/FakeItEasy/A.cs
src/FakeItEasy/Core/InterceptedFakeObjectCallExtensions.cs
src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
src/FakeItEasy/Creation/IDummyValueResolver.cs
src/FakeItEasy/Creation/IFakeAndDummyManager.cs
src/FakeItEasy/Creation/IFakeObjectCreator.cs
src/FakeItEasy/Creation/LoopDetectingResolutionContext.cs
src/FakeItEasy/Creation/ResolvedConstructor.cs
src/FakeItEasy/Fake.of.T.cs
src/FakeItEasy/Sdk/Create.cs
tests/FakeItEasy.Specs/ClassWithLongSelfReferentialConstructor.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Tests/Creation/DefaultFakeObjectCreatorTests.cs
tests/FakeItEasy.Tests/Creation/DummyValueResolverTests.cs

Detect fake loops

---

tools/FakeItEasy.Build/Program.cs

shorten input values in build logs

---

tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi40.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApi45.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd16.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.ApproveApiNetStd20.approved.txt
tests/FakeItEasy.Tests.Approval/ApiApproval.cs
tests/FakeItEasy.Tests.Approval/FakeItEasy.Tests.Approval.csproj

Update PublicApiGenerator to 9.3.0

---

src/FakeItEasy/Core/FakeManager.ObjectMemberRule.cs
src/FakeItEasy/Core/MethodInfoManager.cs
src/FakeItEasy/Core/WrappedObjectRule.cs
src/FakeItEasy/MethodBaseExtensions.cs
src/FakeItEasy/ObjectMembers.cs
tests/FakeItEasy.Specs/WrappingFakeSpecs.cs

Fix equality for wrapping fakes

---

src/FakeItEasy/Core/ArgumentConstraintTrap.cs
src/FakeItEasy/Core/DefaultArgumentConstraintManager.cs
src/FakeItEasy/Core/IArgumentConstraintTrapper.cs
src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Tests/Core/ArgumentConstraintTrapTests.cs
tests/FakeItEasy.Tests/Expressions/ExpressionArgumentConstraintFactoryTests.cs

Reject multi-constraint argument constraint factories

---

src/FakeItEasy/Core/ArgumentConstraintTrap.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs

Continue to detect illegal argument constraint creation after failed argument constraint factory invocation

---

docs/dummies.md
src/FakeItEasy/Creation/DummyValueResolver.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj

Support for creating dummy tuples

---

src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/UserCallbackExceptionSpecs.cs

Wrap exception from argument constraint factory

---

src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
tests/FakeItEasy.Specs/UserCallbackExceptionSpecs.cs

Stop wrapping action callback exceptions

---

src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
src/FakeItEasy/Creation/LoopDetectingResolutionContext.cs
tests/FakeItEasy.IntegrationTests/DummyTests.cs

Prevent stack overflow when competing threads resolve same Dummy type

---

src/Directory.Build.props
tools/Directory.Build.props
tools/FakeItEasy.Build/FakeItEasy.Build.csproj

update Bullseye, SimpleExec, and MinVer to RTM

---

src/FakeItEasy.Analyzer.CSharp/FakeItEasy.Analyzer.CSharp.csproj
src/FakeItEasy.Analyzer.Shared/ArgumentConstraintAnalyzerBase.cs
src/FakeItEasy.Analyzer.Shared/ArgumentConstraintTypeMismatchAnalyzer.cs
src/FakeItEasy.Analyzer.Shared/ArgumentConstraintTypeMismatchCodeFixProvider.cs
src/FakeItEasy.Analyzer.Shared/NonVirtualSetupAnalyzer.cs
src/FakeItEasy.Analyzer.Shared/RepeatedAssertionAnalyzer.cs
src/FakeItEasy.Analyzer.Shared/UnusedReturnValueAnalyzer.cs
src/FakeItEasy.Analyzer.VisualBasic/FakeItEasy.Analyzer.VisualBasic.csproj
tests/FakeItEasy.Analyzer.CSharp.Tests/FakeItEasy.Analyzer.CSharp.Tests.csproj
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/DiagnosticVerifier.Helper.cs
tests/FakeItEasy.Analyzer.Tests.Shared/Helpers/DiagnosticVerifier.cs
tests/FakeItEasy.Analyzer.VisualBasic.Tests/FakeItEasy.Analyzer.VisualBasic.Tests.csproj

Cherry-picked the commits from my current work on https://github.com/FakeItEasy/FakeItEasy/issues/1662, I hope it didn't depend on anything I didn't include...

Upgrade analyzers to .NET Standard 2.0 and test them on .NET Core

---

src/Directory.Build.props
src/FakeItEasy.Analyzer.Shared/FakeItEasy.Analyzer.Shared.projitems
src/FakeItEasy.Extensions.ValueTask/FakeItEasy.Extensions.ValueTask.csproj
src/FakeItEasy/FakeItEasy.csproj
tools/FakeItEasy.Build/FakeItEasy.Build.csproj
tools/FakeItEasy.Build/Program.cs

Use SourceLink

---

src/FakeItEasy/Creation/DummyValueResolver.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs

Create lazy dummies lazily

---

src/Directory.Build.props
src/FakeItEasy.Analyzer.Shared/FakeItEasy.Analyzer.Shared.projitems

Enable package analysis

---

src/FakeItEasy/Creation/DummyValueResolver.cs

Remove unused funcType variable

---

FakeItEasy.sln
src/FakeItEasy/ReturnValueConfigurationExtensions.StronglyTyped.cs
src/FakeItEasy/ReturnValueConfigurationExtensions.StronglyTyped.tt
tools/ReleaseHelpers.cs

A few small things that didn't belong anywhere else...

Various fixes

---

src/FakeItEasy.Analyzer.Shared/ArgumentConstraintTypeMismatchCodeFixProvider.cs
src/FakeItEasy.Analyzer.Shared/SymbolExtensions.cs
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/RootModule.cs
src/FakeItEasy/StringBuilderOutputWriter.cs
src/FakeItEasy/ValueProducerSignatureHelper.cs
tests/FakeItEasy.Tests/Core/ArgumentValueFormatterTests.cs
tests/FakeItEasy.Tests/Creation/CastleDynamicProxy/CastleDynamicProxyGeneratorTests.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallMatcherTests.cs

Contributes to #1613.   
I started this work before we got the 3.0 SDK, so I didn't want to make language-level changes. I think it's still valuable. I'm not married to any particular approach, and if we want to address some things differently, I'm happy to update or to just drop the commit and revisit later, as there are still quite a number of warnings to clean up, in addition to an API review and so on. I will update #1613 soonish with a task list (it might be small) as well as thoughts on how we should continue there.

Reduce nullability warnings

---

tools/FakeItEasy.Build/Program.cs

… I get tired of copying files manually.

Add target to approve new public API

---

profiles/full.props

Run approval tests under netcoreapp3.0 in the full build profile

---

tools/FakeItEasy.PrepareRelease/Program.cs

Have prepare-release manage support releases

---

src/FakeItEasy/Core/CompletedFakeObjectCall.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/ICompletedFakeObjectCall.cs
src/FakeItEasy/Core/InterceptedFakeObjectCall.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs
tests/FakeItEasy.Specs/FakeSpecs.cs
tests/FakeItEasy.Tests/Core/FakeManagerTests.cs

Fixes #1696 
~~WIP because I want to try another approach~~ Scratch that, my idea won't work...

Record ReturnValue on CompletedFakeObjectCall

---

docs/advanced-usage.md
src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/Core/FakeManager.ObjectMemberRule.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/Fake.cs
tests/FakeItEasy.Specs/FakeSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt
tests/FakeItEasy.Tests/FakeTests.cs

The support/5.x branch does not compile for me, as I have no GetTypeInformation() method for System.Type. I guess it should be GetTypeInfo()... or am I missing something?

Fix for issue #1709 - now targeting 5.x support 

---

tests/FakeItEasy.Specs/FakeSpecs.cs

Fix typo in FakeSpecs spec text

---

src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/Fake.cs
src/FakeItEasy/FakeObjectCallExtensions.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt

Add nullability annotations to public API

---

src/FakeItEasy/Configuration/AnyCallConfiguration.cs
src/FakeItEasy/Configuration/IAnyCallConfigurationWithNoReturnTypeSpecified.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt

Annotate WithNonVoidReturnType to include nullable reference return types

---

tests/FakeItEasy.Specs/ArgumentMatchingSpecs.cs
tests/FakeItEasy.Specs/AssertingCallCountSpecs.cs
tests/FakeItEasy.Specs/CallDescriptionsInAssertionSpecs.cs
tests/FakeItEasy.Specs/CallMatchingSpecs.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Specs/ConfiguringPropertySetterSpecs.cs
tests/FakeItEasy.Specs/CreationOptionsSpecs.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/DisposableSpecs.cs
tests/FakeItEasy.Specs/DomainEvents.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Specs/DummyFactorySpecs.cs
tests/FakeItEasy.Specs/EventRaisingSpecs.cs
tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
tests/FakeItEasy.Specs/FakeSpecs.cs
tests/FakeItEasy.Specs/FakingDelegates.cs
tests/FakeItEasy.Specs/MakesVirtualCallInConstructor.cs
tests/FakeItEasy.Specs/UnconfiguredFakeSpecs.cs
tests/FakeItEasy.Specs/UserCallbackExceptionSpecs.cs
tests/FakeItEasy.Specs/WrappingFakeSpecs.cs
tests/FakeItEasy.Tests/ACallToTests.cs

Contributes to #1691.
In fact, I believe this to be the last of the nullability work. Once it's (changed according to review comments and squashed and) merged, we can probably merge nullability to master.
On that point, do we want to reshape nullability before merging? Squash some of the existing commits? Elide the merge commits? We can talk about this later.

Quell nullability warnings in specs

---

src/FakeItEasy/Compatibility/MaybeNullAttribute.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt

Make MaybeNull attribute internal

---

tests/FakeItEasy.Tests.Approval/ApiApproval.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy.Extensions.ValueTask/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy.Extensions.ValueTask/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy.Extensions.ValueTask/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt
tests/FakeItEasy.Tests.Approval/FakeItEasy.Tests.Approval.csproj

I'm perfectly happy to rebase after #1718 merges.

Upgrade ApiGenerator to 10.0.0

---

src/FakeItEasy/Core/ArgumentValueFormatter.cs

Completes #1734.
I don't know how I missed the warning!

Quiet warning about catching general exception in ArgumentValueFormatter

---

appveyor.yml

To fix those warnings: https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/builds/29381954/job/05b8bnjmcta3p480#L77
Supports #1735.

Update submodules before build

---

src/FakeItEasy/ArgumentConstraintManagerExtensions.cs

By using ordinal string comparison
Fixes issue mentioned in https://github.com/FakeItEasy/FakeItEasy/issues/1681#issuecomment-573030653

Fix Contains argument constraint

---

docs/argument-constraints.md
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringContainsWithComparisonTypeTests.cs

Add Contains overload with a StringComparison

---

docs/analyzer.md
mkdocs.yml

Supports FakeItEasy/FakeItEasy.Analyzers#20.

Provide consistent analyzer/analyzers usage in documentation

---

src/FakeItEasy/Configuration/OutAndRefParameters.StronglyTyped.cs
src/FakeItEasy/Configuration/OutAndRefParameters.StronglyTyped.tt
src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidator.cs
src/FakeItEasy/Creation/DummyValueResolver.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs

Improve error message for explicit implementation of interface method

---

docs/specifying-a-call-to-configure.md

Relates to #1759
I'm not completely happy with the wording, feel free to suggest improvements!

Document configuration of explicit interface implementation

---

docs/strict-fakes.md
src/FakeItEasy/Core/StrictFakeRule.cs
src/FakeItEasy/FakeOptionsExtensions.cs
src/FakeItEasy/StrictFakeOptions.cs
tests/FakeItEasy.Specs/StrictFakeSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt

Strict fake options

---

src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/RootModule.cs

Throw exception when bootstrapper returns null

---

docs/argument-constraints.md
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringEndsWithTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringEndsWithWithComparisonTypeTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringStartsWithTests.cs
tests/FakeItEasy.Tests/ArgumentConstraintManagerExtensions/StringStartsWithWithComparisonTypeTests.cs

Support StringComparison in EndsWith and StartsWith constraints

---

src/FakeItEasy/Compatibility/AllowNullAttribute.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Tests/Core/MethodInfoManagerTests.cs

Fix warnings

---

docs/doing-nothing.md

Inspired by #1781. I also made some other notes to make the usage a little more clear. (I hope).

Explain that DoesNothing only applies to void members

---

docs/doing-nothing.md
src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/ReturnValueConfigurationExtensions.cs
src/FakeItEasy/TaskHelper.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net40.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard1.6.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt

Add DoesNothing method for task-returning methods

---

docs/invoking-custom-code.md
docs/specifying-a-call-to-configure.md

Provide case study of customizing read/write property's setter

---

docs/creating-fakes.md
docs/default-fake-behavior.md
docs/dummies.md
docs/implicit-creation-options.md

fixes various typos

---

src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/Configuration/FakeConfigurationManager.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Core/ArgumentValueFormatter.cs
src/FakeItEasy/Core/EventHandlerArgumentProviderMap.cs
src/FakeItEasy/Core/FakeCallEqualityComparer.cs
src/FakeItEasy/Core/FakeManager.EventRule.cs
src/FakeItEasy/Core/FakeManager.ObjectMemberRule.cs
src/FakeItEasy/Core/FakeManager.PropertyBehaviorRule.cs
src/FakeItEasy/Core/FakeManager.PropertySetterRule.cs
src/FakeItEasy/Core/FakeManager.cs
src/FakeItEasy/Core/MethodInfoManager.cs
src/FakeItEasy/Core/TypeCatalogue.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidator.cs
src/FakeItEasy/Creation/CreationResult.cs
src/FakeItEasy/Creation/FakeAndDummyManager.cs
src/FakeItEasy/Creation/FakeObjectCreator.cs
src/FakeItEasy/Creation/ProxyGeneratorResult.cs
src/FakeItEasy/ExpressionExtensions.cs
src/FakeItEasy/Fake.cs
src/FakeItEasy/LinkedListExtensions.cs
src/FakeItEasy/TypeExtensions.cs
tests/FakeItEasy.Specs/ArgumentMatchingSpecs.cs
tests/FakeItEasy.Specs/FakeOptionsBuilderSpecs.cs
tests/FakeItEasy.Tests/CustomArgumentConstraints.cs
tests/FakeItEasy.Tests/NullGuardedAssertion.cs

Move to 'not null' pattern

---

docs/advanced-usage.md
src/FakeItEasy/Fake.cs
tests/FakeItEasy.IntegrationTests/ConcurrentCallTests.cs
tests/FakeItEasy.Specs/FakeSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net5.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt
tests/FakeItEasy.Tests/FakeTests.cs

Deprecate ClearConfiguration

---

FakeItEasy.sln
docs/scanning-for-extension-points.md
src/FakeItEasy/Core/TypeCatalogue.cs
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.IntegrationTests/EnsureReference.cs
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs
tests/FakeItEasy.Tests.ExtensionPoints/DayOfWeekDummyFactory.cs
tests/FakeItEasy.Tests.ExtensionPoints/FakeItEasy.Tests.ExtensionPoints.csproj

As discussed in chat with @blairconrad
WIP because I still need to implement "light loading" of assemblies for TFMs that don't have `ReflectionOnlyLoad`.

Better extension point scanning

---

README.md

the 256px version looks quite nasty on a high DPI screen

Switch logo to high DPI 512px

---

docs/argument-constraints.md
src/FakeItEasy/A.cs
src/FakeItEasy/A.of.T.cs
src/FakeItEasy/An.of.T.cs
src/FakeItEasy/IHideObjectMembers.cs
src/FakeItEasy/Sdk/Create.cs
tests/FakeItEasy.Specs/AnArgumentConstraintSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net5.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt

Contributes to #1819
(not closing the issue, because we also need to update FakeItEasy.Analyzers)

An<T> argument constraints

---

src/FakeItEasy/Expressions/CallExpressionParser.cs
tests/FakeItEasy.Specs/UnnaturalFakeSpecs.cs

Support argument constraints with parameters when used with unnatural constraints

---

src/FakeItEasy/Creation/DummyValueResolver.cs
src/FakeItEasy/Creation/FakeAndDummyManager.cs
src/FakeItEasy/Creation/IProxyOptionsFactory.cs
src/FakeItEasy/Creation/ProxyOptionsFactory.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Tests/Creation/DummyValueResolverTests.cs

Apply implicit creation options to dummy fakes

---

src/FakeItEasy/A.cs
src/FakeItEasy/Sdk/Create.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net45.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net5.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.approved.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.approved.txt

Add CollectionOfFake overloads that accept an action that uses fake number to configure fake

---

src/FakeItEasy/Configuration/AnyCallCallRule.cs
src/FakeItEasy/Configuration/FakeConfigurationManager.cs
src/FakeItEasy/Configuration/PropertyExpressionHelper.cs
src/FakeItEasy/Configuration/StartConfiguration.cs
src/FakeItEasy/Core/DefaultFakeObjectCallFormatter.cs
src/FakeItEasy/Expressions/CallConstraintDescriber.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
tests/FakeItEasy.Specs/AnyCallConfigurationSpecs.cs
tests/FakeItEasy.Specs/CreationSpecs.cs
tests/FakeItEasy.Specs/OrderedCallMatchingSpecs.cs
tests/FakeItEasy.Specs/StrictFakeSpecs.cs
tests/FakeItEasy.Tests/Expressions/ExpressionCallMatcherTests.cs

Include defined Fake name in exception messages.

---

FakeItEasy.sln

I just realized I had not updated the submodule after https://github.com/FakeItEasy/FakeItEasy.Tools/pull/6 was merged...
I also updated the solution file to remove missing files and add shared files from tools-shared

Modernize tools

---

src/FakeItEasy/Configuration/RuleBuilder.cs
tests/FakeItEasy.Specs/WrappingFakeSpecs.cs

Ensure that CallsWrappedMethod adds a rule

---

how_to_build.md
profiles/full.props
profiles/net6.0.props
src/FakeItEasy/ArgumentConstraintManagerExtensions.cs
src/FakeItEasy/Compatibility/CallerArgumentExpressionAttribute.cs
src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyInterceptionValidator.cs
src/FakeItEasy/FakeItEasy.csproj
tests/FakeItEasy.IntegrationTests/FakeItEasy.IntegrationTests.csproj
tests/FakeItEasy.IntegrationTests/StringArgumentConstraints.cs
tests/FakeItEasy.Specs/FakeItEasy.Specs.csproj
tests/FakeItEasy.Specs/IllegalFluentApiSpecs.cs
tests/FakeItEasy.Specs/InParametersSpecs.cs
tests/FakeItEasy.Tests.TestHelpers/FakeItEasy.Tests.TestHelpers.csproj
tests/FakeItEasy.Tests.TestHelpers/StringExtensions.cs

Test against .NET 6.0

---

.github/workflows/docs.yml

Build docs on each pull request

---

docs/analyzer.md
mkdocs.yml

Redirect analyzers docs to docs on FakeItEasy website

---

docs/formatting-argument-values.md

Explain default argument formatting before how to customize

---

.github/workflows/release.yml
.gitignore
FakeItEasy.sln

- Update the tools-shared submodule to get the latest fixes in the deploy script
- Fix the NUGET_SERVER_URL
- Set the GITHUB_TOKEN environment variable

Fix release workflow

---

mkdocs.yml

Read snippets base_path from SNIPPETS_REPO_ROOT environment variable

---

.github/workflows/release.yml

Update tools-shared submodule

---

docs/platform-support.md
mkdocs.yml

Add platform support policy to documentation

---

.github/workflows/publish-docs-preview.yml

Add workflow to publish docs preview when the `when the 👀 publish-docs-preview label` is added to a PR

Publish docs preview

---

src/FakeItEasy/Creation/ResolvedConstructor.cs
tests/FakeItEasy.Specs/CreationSpecs.cs

Enable fake creation via constructors with in parameters

---

FakeItEasy.sln
docs/argument-constraints.md
docs/custom-argument-equality.md
docs/scanning-for-extension-points.md
mkdocs.yml
src/FakeItEasy/ArgumentEqualityComparer.cs
src/FakeItEasy/Core/ArgumentEqualityComparer.cs
src/FakeItEasy/Expressions/ArgumentConstraints/EqualityArgumentConstraint.cs
src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs
src/FakeItEasy/IArgumentEqualityComparer.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Specs/ArgumentEqualityComparerSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net462.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net6.0.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.verified.txt
tests/FakeItEasy.Tests/Expressions/ArgumentConstraints/AggregateArgumentConstraintTests.cs
tests/FakeItEasy.Tests/Expressions/ArgumentConstraints/EqualityArgumentConstraintTests.cs

Fixes #1952
Note: the build will fail until #1954 is merged

Custom argument equality comparers

---

requirements.txt

Update docs-building dependencies

---

docs/dummies.md
src/FakeItEasy/Creation/DummyValueResolver.cs
tests/FakeItEasy.Specs/ConfigurationSpecs.cs
tests/FakeItEasy.Specs/DummyCreationSpecs.cs
tests/FakeItEasy.Tests/Creation/DummyValueResolverTests.cs

Don't attempt to create void dummy

---

Directory.Build.props
src/FakeItEasy/Core/CompletedFakeObjectCall.cs
tools/FakeItEasy.Build/Program.cs

Updated rules will work better with collection expressions when we start using them.

Upgrade StyleCop

---

FakeItEasy.sln
docs/argument-constraints.md
docs/capturing-arguments.md
mkdocs.yml
recipes/FakeItEasy.Recipes.CSharp/CapturingArguments.cs
src/FakeItEasy/A.cs
src/FakeItEasy/Captured.of.TArgument.TCapture.cs
src/FakeItEasy/Captured.of.TArgument.cs
src/FakeItEasy/Configuration/BuildableCallRule.cs
src/FakeItEasy/Configuration/RuleBuilder.cs
src/FakeItEasy/Core/DefaultArgumentConstraintManager.cs
src/FakeItEasy/Core/IHaveASideEffect.cs
src/FakeItEasy/ExceptionMessages.cs
src/FakeItEasy/Expressions/ExpressionCallMatcher.cs
src/FakeItEasy/Expressions/ExpressionCallRule.cs
src/FakeItEasy/Guard.cs
src/FakeItEasy/IArgumentConstraintManagerFactory.cs
src/FakeItEasy/ICapturableArgumentConstraintManager.cs
src/FakeItEasy/RootModule.cs
tests/FakeItEasy.Specs/ArgumentCapturingSpecs.cs
tests/FakeItEasy.Specs/FluentApiSpecs.cs
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net462.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/net6.0.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.0.verified.txt
tests/FakeItEasy.Tests.Approval/ApprovedApi/FakeItEasy/netstandard2.1.verified.txt
tests/FakeItEasy.Tests/Captured.of.TArgument.Tests.cs
tests/FakeItEasy.Tests/Configuration/BuildableCallRuleTests.cs
tests/FakeItEasy.Tests/Configuration/RuleBuilderTests.cs
tests/FakeItEasy.Tests/NullGuardedAssertionTests.cs

Provide a mechanism for capturing arguments passed to Fakes

---

README.md
src/Directory.Build.props

Embed readme

---

.github/workflows/ci.yml
.github/workflows/release.yml

To fix these [build warnings](https://github.com/FakeItEasy/FakeItEasy/actions/runs/8573142701):

Update Github actions to latest

---

.github/workflows/publish-docs-preview.yml

Fix docs preview workflow

---

src/FakeItEasy/Creation/DelegateProxies/CastleInvocationDelegateCallAdapter.cs
src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs

Use DynamicProxy's CreateDelegateToMixin to fake delegates

---

docs/argument-constraints.md
docs/specifying-a-call-to-configure.md

Explain how to use Where to match calls with anonymous types

---

how_to_build.md

I also took the liberty of rearranging the .md a bit, mostly to make it easier to update in the future!

Correct how to build lies, now that we're in a .NET 8.0 world

---

.github/workflows/ci.yml
docs/how-to-build.md
profiles/full.props

Test on macos-15 instead of macos-12

---

.github/workflows/ci.yml
docs/.linkcheckerrc
tools/FakeItEasy.Build/Program.cs

Check readme links
